tools/transform.h
util/compiler.cpp

clang doesn't seem to have the sign bit detection builtin and it's also a bit pickier about struct vs class

clang fixes

---

.travis.yml

NB this won't do anything until https://github.com/AliveToolkit/alive2/pull/4 is merged

make sure to run sanitizers during CI testing

---

README.md
scripts/opt-alive.sh

the tiny opt replacement script

document translation validation as explained to me by Nuno and add

---

tools/alive-tv.cpp

- call initializer earlier
- make sure alive parsing succeeded
and also support processing both .ll and .bc files

fix two bugs:

---

ir/instr.cpp
tests/unit/vector/vadd.opt

Hi @nunoplopes , this is a draft implementation of vector binary operator, I would like to take your opinion as early as possible. I'll continue working on this only if you're okay with the approach :)

Binary operators for vectors

---

tools/alive-tv.cpp

one. Matching is done by name.

Make alive-tv process all functions in its input modules, not just

---

tools/alive-tv.cpp

sorry, meant to do this earlier

oops -- we no longer get newlines for free on errors

---

scripts/opt-alive.sh
scripts/stats.php
tests/lit/lit/formats/alive2test.py

A few lines of patch that fixes scripts.

Fix scripts

---

ir/memory.cpp
scripts/opt-alive.sh

.. and minor things
- Ignore `-insert-gconv-profiling` pass

Check validity of the value in Memory::store's assertion

---

llvm_util/llvm2alive.cpp
llvm_util/utils.cpp
tests/alive-tv/memory/glb-anonymous-2.src.ll
tests/alive-tv/memory/glb-anonymous-2.tgt.ll
tests/alive-tv/memory/glb-anonymous.src.ll
tests/alive-tv/memory/glb-anonymous.tgt.ll

This resolves issue #209 . It works pretty well.
LLVM unit tests failure: 136 -> 129

Support anonymous global variables

---

ir/memory.cpp
ir/type.cpp

Fixes Transforms/ConstProp/loads.ll

Support empty array

---

llvm_util/llvm2alive.cpp
tests/alive-tv/memory/lifetime-1.src.ll
tests/alive-tv/memory/lifetime-1.tgt.ll

This is the first PR for lifetime support.
This converts lifetime into a trivial op.

Convert lifetime into a trivial op

---

tv/tv.cpp

This resolves opt-alive.sh failure on Transforms/Reassociate/pointer-collision-non-determinism.ll .
To explain how this patch works, assume that two `-tv` command arguments are given to opt. Originally, steps are:
1. Two TVPass instances are created
2. Their doInitialization() are called
3. runFunction() called
4. doFinalization() are called
Given -run-twice, 2 ~ 4 are repeated once more.
Previously, doInitialization()'s done variable was set to true at the step 2, leading to never initializing TVPass again after doFinalization() was called when -run-twice was given.
This patch resolves the issue by counting doInitialization() and doFinalization() calls and using the counter to re-initialize.
The report file is created only once (note that pointer-collision-non-determinism.ll has two …

Let tv work when -run-twice is given

---

tests/alive-tv/memory/alloca-align.src.ll
tests/alive-tv/memory/alloca-align.tgt.ll

Add tests that make alloca use more memory.

Add tests that make alloca use more memory

---

ir/globals.cpp
ir/globals.h
ir/memory.cpp
ir/memory.h
ir/value.cpp
ir/value.h
llvm_util/llvm2alive.cpp
tests/alive-tv/attrs/readonly.src.ll
tests/alive-tv/attrs/readonly.tgt.ll
tools/transform.cpp

This PR supports readonly using attribute bits of a pointer.

Support readonly

---

ir/memory.cpp
ir/state.h
tests/alive-tv/memory/alloca-removal-fail.src.ll
tests/alive-tv/memory/alloca-removal-fail.tgt.ll
tests/alive-tv/memory/alloca-removal.src.ll
tests/alive-tv/memory/alloca-removal.tgt.ll
tests/alive-tv/memory/malloc-undef.src.ll
tools/transform.cpp

This PR adds a notion of OOM to support removal of local blocks even when addresses are observed.

Add a notion of OOM

---

tests/alive-tv/bugs/pr31243.srctgt.ll
tests/alive-tv/bugs/pr43948.srctgt.ll

This PR adds a test for reproducing bugs from bugzilla.

Add tests from bugzilla

---

tests/alive-tv/bugs/README.md
tests/alive-tv/bugs/pr1261.srctgt.ll
tests/alive-tv/bugs/pr21256.srctgt.ll
tests/alive-tv/bugs/pr23038.srctgt.ll
tests/alive-tv/bugs/pr3720.srctgt.ll
tests/alive-tv/bugs/pr37540.srctgt.ll
tests/alive-tv/bugs/pr4374.srctgt.ll

I'll be back soon & keep digging bugzilla
Note that these contains miscompilation on non-memory ops as well

Add more bugs from bugzilla, add README

---

ir/state.cpp
ir/state.h

This helps improve readability of State::addFnCall  and State::syncSEdataWithSrc.

Factor out data structures used by fn_call_data

---

tests/alive-tv/bugs/pr43616.src.ll
tests/alive-tv/bugs/pr43616.tgt.ll

Sorry for delay, this is a PR with pr43616.src/tgt.ll only

Add pr43616 test

---

BugList.md
README.md

It will be great if there is a page for enumerating bugs that we've found using Alive2. :)
The bugs that I have are only listed here.. I guess there must be more!

List LLVM bugs found by Alive2

---

llvm_util/llvm2alive.cpp
tests/alive-tv/extractvalue-padding.srctgt.ll

Resolve a crash of Transforms/ConstProp/extractvalue.ll .

Resolve regression after #356

---

ir/attrs.h
ir/instr.cpp
ir/instr.h
ir/state.cpp
ir/state.h
llvm_util/llvm2alive.cpp

This PR factors out function attributes as FnAttrs class.

Factor out FnAttrs class

---

ir/constant.cpp
ir/constant.h
ir/instr.cpp
ir/instr.h
ir/type.cpp
ir/type.h
tests/alive-tv/opt-memory/alloca.srctgt.ll
tests/alive-tv/opt-memory/calloc.srctgt.ll
tests/alive-tv/opt-memory/memaccess-strlen.srctgt.ll
tools/transform.cpp

This PR defines MemInstr and makes memory related instructions inherit this class.

Define MemInstr & let memory related classes inherit from this

---

BugList.md

These are 2 Z3 bugs that I've found.

Add two Z3 bugs

---

ir/state.cpp

Memory::refined may take a long time if there are big constant strings (expr::load called by blockValRefined can go deep).
Encoding function calls is the place where Memory::refined is frequently called; this PR reduces the number of its invocation.
This halves preprocessing time of inputs that take long time from gzip and bzip2.

Early exit if refines.isFalse holds

---

tests/alive-tv/bugs/pr10067.srctgt.ll
tests/alive-tv/bugs/pr11390.srctgt.ll
tests/alive-tv/bugs/pr18223.srctgt.ll
tests/alive-tv/bugs/pr23599.srctgt.ll
tests/alive-tv/bugs/pr24179.srctgt.ll
tests/alive-tv/bugs/pr29034.src.ll
tests/alive-tv/bugs/pr29034.tgt.ll
tests/alive-tv/bugs/pr32078.srctgt.ll
tests/alive-tv/bugs/pr41949-2.srctgt.ll

Alive2 cannot find bugs from these pairs, and I wrote down the reasons at the header of each file.

Add unsupported bugs from bugzilla

---

BugList.md
tests/alive-tv/bugs/pr46591.srctgt.ll

Add pr46591

---

ir/memory.cpp
tests/alive-tv/refinement/null-glb-fail.srctgt.ll

Will leave experimental results here after they're done

Stricter refinement check for nonlocals

---

llvm_util/llvm2alive.cpp

This adds the missing update from the patch for supporting for noundef.

Parse noundef

---

ir/memory.cpp
ir/state.cpp

This is a simple patch that does minor refactoring to State::addFnCall and Memory::mkFnRet.

Minor refactoring to fn call add

---

tv/tv.cpp

Broken after https://reviews.llvm.org/D81555 / https://github.com/llvm/llvm-project/commit/18bc400f97a64a23c8ce97873a0c4d958faf0f95

Fix TV build against current llvm master

---

ir/instr.cpp
tests/alive-tv/memory/malloc-noundef.srctgt.ll
tests/alive-tv/memory/malloc-poison-ub.srctgt.ll

As discussed, this is a patch that makes malloc(poison) UB.

Make malloc(poison) UB

---

ir/instr.cpp
tests/alive-tv/attrs/noreturn-fail-6.srctgt.ll

Raise UB when returning from noreturn fn

---

CMakeLists.txt
ir/function.cpp
ir/function.h
tools/alive-tv.cpp
util/unionfind.cpp
util/unionfind.h

Implementing Tarjan's Loop Analysis Algorithm

---

ir/instr.cpp
ir/instr.h
llvm_util/llvm2alive.cpp
tests/alive-tv/attrs/noundef-bundle.srctgt.ll
tools/alive_parser.cpp

Add support for llvm.assume with noundef op bundle

---

CMakeLists.txt
README.md
tools/alive-exec.cpp

Nuno will fill in the hard part at the location marked FIXME
let's remember to do some factoring out of common code between utilities sometime. I started doing that here but it got messy so I think it's best done in a separate branch.

add skeleton of a new tool that attempts to execute IR functions using alive2 as an interpreter

---

tv/tv.cpp

This PR resolves the core problem of issue #516 - after a pass is skipped because e.g., it is an interprocedural pass, clang plugin wasn't properly updating fns map.

clang plugin: fns should be updated even if a pass is skipped

---

tv/tv.cpp
util/stopwatch.cpp
util/stopwatch.h

This PR adds `-tv-elapsed-time` that prints the running time of TV.

Add -tv-elapsed-time

---

ir/function.cpp
ir/function.h
ir/instr.cpp
ir/instr.h
tools/alive-exec.cpp
tools/alive-tv.cpp
tools/transform.cpp
tv/tv.cpp
util/config.cpp
util/config.h

Unrolling without handling phis

---

ir/function.cpp
ir/function.h
ir/instr.cpp
ir/instr.h

@nunoplopes Hi Nuno, I have one question, how do we deal with multiple loops share one common header? Should we canonicalize the loop  before unrolling?

step 2,  fix phi nodes inside loops

---

ir/attrs.cpp
ir/attrs.h
ir/instr.cpp
ir/memory.cpp
llvm_util/llvm2alive.cpp
tests/alive-tv/attrs/align-callsite.srctgt.ll
tests/alive-tv/attrs/align-callsite2.srctgt.ll
tests/alive-tv/attrs/align-callsite3.srctgt.ll
tests/alive-tv/attrs/align-fndef.srctgt.ll
tests/alive-tv/attrs/align-fndef2.srctgt.ll
tests/alive-tv/attrs/align-ret-callsite.srctgt.ll
tests/alive-tv/attrs/align-ret-callsite2.srctgt.ll

This PR adds support for align attribute.
It is analogous to nonnull; violating the alignment condition is UB.

Add support for align attribute

---

ir/state.cpp
tests/alive-tv/undef/strip-add-eq.srctgt.ll
tests/alive-tv/undef/strip-add-ule.srctgt.ll

Add more patterns to strip_undef_and_add_ub

---

llvm_util/utils.cpp
tests/alive-tv/poison-fail.srctgt.ll
tests/alive-tv/poison.srctgt.ll
tests/alive-tv/undef/poison-fail.srctgt.ll
tests/alive-tv/undef/poison.srctgt.ll

This PR adds support for the poison constant newly added to LLVM.

add support for poison constant

---

CMakeLists.txt
README.md
scripts/gen-dashboard.php
tests/lit/lit/formats/alive2test.py
tv/CMakeLists.txt

just making these easier for people to find!

put alivecc, alive++, and opt driver into the main build dir instead of a subdir

---

tv/tv.cpp

After #616 is merged, this PR should be rebased.

switch to module pass

---

tv/tv.cpp
util/parallel.cpp
util/parallel.h
util/parallel_jobserver.cpp
util/parallel_unrestricted.cpp

overall this is quite a bit better and more robust code than before, I hope that the basic parallel mode is more or less finished now

Parallel mode fixed

---

tests/alive-tv/attrs/align-issue625.srctgt.ll
tools/transform.cpp

take return value's align into consideration

---

smt/solver.cpp
smt/solver.h
tools/transform.cpp

This is a patch to lazily call preprocess to shorten VCGen time.

Lazily call preprocess to shorten vcgen time

---

smt/exprs.h
tools/transform.cpp

not totally sure about the second one...

fix two things that block compilation using latest g++

---

ir/attrs.cpp
ir/instr.cpp
tests/alive-tv/undef/load-undefidx.srctgt.ll

Dereferenced pointers are noundef

---

ir/instr.cpp

This patch deduplicates the return value's attr encoding in pack_return and Return::toSMT.

refactor code duplication in a return value's attr encoding

---

tools/alive-tv.cpp

Reverts AliveToolkit/alive2#687

Revert "fix build against latest llvm"

---

ir/attrs.h
ir/instr.cpp
ir/instr.h
llvm_util/llvm2alive.cpp

This PR resolves #560 .
Running LLVM unit tests...

refactor LLVM -> Alive2 attributes mapping

---

BugList.md

Add the align operand bundle bug

---

README.md

Update README on how to load tv.so into opt

---

ir/attrs.cpp
ir/constant.cpp
ir/fast_math.cpp
ir/function.cpp
ir/instr.cpp
ir/instr.h
ir/memory.cpp
ir/pointer.cpp
ir/precondition.cpp
ir/state.cpp
ir/state_value.cpp
ir/type.cpp
ir/value.cpp
llvm_util/known_fns.cpp
llvm_util/llvm2alive.cpp
llvm_util/utils.cpp
smt/expr.cpp
smt/exprs.cpp
smt/smt.cpp
smt/solver.cpp
tools/alive-exec.cpp
tools/alive-tv.cpp
tools/alive_lexer.re
tools/alive_parser.cpp
tools/transform.cpp
tv/tv.cpp
util/errors.cpp
util/parallel.cpp
util/stopwatch.h

Please do not kill the messenger.
Yes, this very much looks like insanity,
yet https://reviews.llvm.org/D119670 / https://github.com/llvm/llvm-project/commit/70b1f6de539867353940d3dcb8b25786d5082d63
i think basically implies that the former will be forbidden
in future versions of the standard.
In the end, i just want to be able to build alive to check my transform :)

Fix build with recent clang

---

tools/alive-jobserver.cpp

needed, we're leaking them at a low rate sometimes and I'm not sure why -- this seems like a reasonably robust, if incredibly hacky, workaround

add some logic to the jobserver to replenish concurrency tokens when

---

tv/tv.cpp

let's just avoid using CloneModule, not only is it slow and leaky, but also it contains a couple of correctness bugs

avoid using LLVM's CloneModule

---

CMakeLists.txt
llvm_util/compare.cpp
llvm_util/compare.h
tools/alive-tv.cpp
tools/quick-fuzz.cpp

the tool is called quick-fuzz instead of bb-fuzz because I'd like to add a few more little fuzzers like this to it in the future
also factor out some common machinery from alive-tv.cpp
I'm not necessarily happy with how the factoring came out but on the other hand I don't think it's all that bad

add a small basic block fuzzer that has already found a few bugs

---

tools/quick-fuzz.cpp

ok I pushed on this one hard enough that it's finding real value mismatches, but I haven't reported them yet. I think this is a useful thing to have in our repo!

another fuzzer

---

ir/instr.cpp
ir/instr.h
llvm_util/llvm2alive.cpp
tests/alive-tv/nneg.srctgt.ll

This patch adds support for nneg flags to uitofp, which was introduced by https://github.com/llvm/llvm-project/pull/86141.

Add support for uitofp nneg

---

ir/instr.cpp
ir/instr.h
ir/pointer.cpp
ir/pointer.h
llvm_util/llvm2alive.cpp
smt/expr.cpp
smt/expr.h
tests/alive-tv/gep.nusw.nuw.srctgt.ll
tools/transform.cpp

I'm struggling to make this actually work, test 4 and 5 currently fail. The problem is that for these flags we can't just require no overflow on the offset, we need to consider the address. However, the offset is one bit smaller than the offset, so we don't get the correct overflow properties. Some advice would be welcome.

Add support for getelementptr nusw and nuw flags (WIP)

---

ir/instr.cpp
tests/alive-tv/uscmp.srctgt.ll

Fixes https://github.com/AliveToolkit/alive2/pull/1049/files#r1633629082.

Fix bitwidth for vector ucmp/scmp

---

ir/function.cpp
ir/function.h

As proposed previously in https://github.com/AliveToolkit/alive2/issues/1075, this PR attempts to improve upon the existing BasicBlock API.

Improve BasicBlock API
