AliveToolkit/alive2

tv/CMakeLists.txt
LLVM needed to be built using -DLLVM_ENABLE_ASSERTIONS=ON, but
what's needed is really -DLLVM_ENABLE_EH=ON
=> the cmake error message when building tv mode suggested that

CMakeLists.txt, README.md
I think this is the right fix, at least it makes me able to build alive2 on my mac where z3 lives in a weird spot
=> include Z3_INCLUDE_DIR, not Z3_INCLUDE_DIRS

tv/CMakeLists.txt
add_llvm_loadable_module() was removed here:
https://reviews.llvm.org/D51748
=> use add_llvm_library instead of add_llvm_loadable_module

CMakeLists.txt
Else, all the `lit` output is being buffered, and is flushed after
the target finishes 'building'. In particular, that hides the
progress meter.
Same as https://github.com/google/souper/pull/404
=> CMake: mark 'check' target as using terminal.

tools/alive-tv.cpp
- abort the comparison if the functions don't have identical
signatures (using code copied from FunctionComparator.cpp,
which alas does not export the required functionality)
- optionally also run the reverse refinement check; I like this
because while playing around it's easy to get things backwards
and also I think it's useful to know when functions are actually
equivalent as opposed to there being a non-trivial refinement
=> two minor features

ir/type.cpp, smt/expr.cpp, smt/expr.h
This fixes the issue https://github.com/AliveToolkit/alive2/issues/79#issue-471235675
Example output
```
----------------------------------------
define float @f1(float %abc) {
%0:
%1 = fadd float %abc, 0.000000
ret float %1
}
=>
define float @f1(float %abc) {
%0:
ret float %abc
}
Transformation doesn't verify!
ERROR: Value mismatch
Example:
float %abc = -0.0
Source:
float %1 = +0.0
Target:
Source value: +0.0
Target value: -0.0
```
=> Pretty print for FP zeros

ir/instr.cpp, ir/instr.h, ir/memory.cpp, ir/memory.h, llvm_util/utils.cpp, tests/memcpy/1-src.ll, tests/memcpy/1-tgt.ll, tests/memcpy/2-src.ll, tests/memcpy/2-tgt.ll, tests/memcpy/3-src.ll, tests/memcpy/3-tgt.ll, tests/memcpy/4-src.ll, tests/memcpy/4-tgt.ll
1) Add memcpy's SMT encoding(in memory.cpp).
2) Make Alive2 interpret memset and memcpy correctly(in instr.cpp, instr.h, utils.cpp).
Previous Alive2 doesn't interpret memset and memcpy, because there is no visit function for them.
So basic tests in 'test/memcpy/' made 'LLVM error: Unsupported instruction'.
I fixed it, as a result basic tests which I made are successfully verified by Alive2.
=> add memcpy to alive2

tests/alive-tv/free-noub-2.src.ll, tests/alive-tv/free-noub-2.tgt.ll, tests/alive-tv/free-ub-gep.src.ll, tests/alive-tv/free-ub-gep.tgt.ll
This PR adds tests that check whether freeing nonzero-offset pointer correctly raises undefined behavior.
=> Add a few more tests for checking UBness of free()

ir/memory.cpp, ir/memory.h, tests/alive-tv/freshbid-alloca.src.ll, tests/alive-tv/freshbid-alloca.tgt.ll, tests/alive-tv/freshbid-malloc.src.ll, tests/alive-tv/freshbid-malloc.tgt.ll
This is a small patch that supports no-alias between a function argument and new malloc ( 
#100 , case (1) ).
This is done by making `malloc()` be local, as `alloca` does.
=> A function argument and new malloc should not alias

ir/state.cpp, ir/state.h, ir/type.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/infinite-loop.src.ll, tests/alive-tv/infinite-loop.tgt.ll, tests/alive-tv/unreachable-1.src.ll, tests/alive-tv/unreachable-1.tgt.ll, tests/alive-tv/unreachable-2.src.ll, tests/alive-tv/unreachable-2.tgt.ll, tests/alive-tv/unreachable-fail.src.ll, tests/alive-tv/unreachable-fail.tgt.ll, tests/alive-tv/unreachable-void-1.src.ll, tests/alive-tv/unreachable-void-1.tgt.ll, tests/alive-tv/unreachable-void-2.src.ll, tests/alive-tv/unreachable-void-2.tgt.ll, tools/transform.cpp
This patch addresses the case when source ends with unreachable but target does (and vice versa):
```
define i32 @f() {
unreachable
}
=>
define i32 @f() {
ret i32 0
}
```
The solution this PR suggests is to lower `unreachable` into `assume 0` followed by `ret poison`.
Adding `ret poison` at the last block doesn’t work in the following case:
```
define i32 @f() {
unreachable
bb: ; unreachable block
ret i32 0
}
```
llvm unit tests (compared with master + #106 + #107): 1197 sec -> 1193sec , 133 fails -> 109 fails
=> Deal with the case when either src or tgt has unreachable

ir/memory.cpp, llvm_util/llvm2alive.cpp
I did two minor fix.
1) Pointer must be aligned when bytes in memset (memcpy) is 0.
2) When alignments in memset (memcpy) is zero, make them 1.
=> fix alignment check when bytes is 0

ir/memory.cpp, ir/memory.h, ir/value.cpp, tests/alive-tv/memory/punning-intptr.src.ll, tests/alive-tv/memory/punning-intptr.tgt.ll, tests/alive-tv/memory/punning-ptrint.src.ll, tests/alive-tv/memory/punning-ptrint.tgt.ll, tests/alive-tv/memory/storeptr-fail.src.ll, tests/alive-tv/memory/storeptr-fail.tgt.ll, tests/alive-tv/memory/storeptr.src.ll, tests/alive-tv/memory/storeptr.tgt.ll
This PR implements reading/writing pointer values from memory.
To do this, a new `Byte` class is implemented, and conversion from `vector<Byte>` to `StateValue` and vice versa (`valueToBytes`, `bytesToValue`) are added.
The definition of Byte follows that of Twin Memory Model, with granularity of _bytes_, not bits, for performance. Also there is no instruction in LLVM that supports manipulation of a pointer bit.
A byte is either a pointer byte, which is a pair (ptr, i) meaning the i'th byte of ptr (0 <= i < 8),
or a non-pointer byte, which has 8-bit numeric digit along with 8-bit poison info. 
```
// Pointer byte's representation:
//   +-+------------------+-------------------+----------------+-------------+
//   |1| non-poison byte? | ptr offset        | block id       | byte offset |
// …
```
=> Support reading/writing pointer values from memory 

CMakeLists.txt
Fixes https://github.com/AliveToolkit/alive2/issues/122
References https://github.com/AliveToolkit/alive2/issues/123
=> CMake: bump required version of Z3 to 4.8.5

ir/memory.cpp, ir/memory.h, ir/value.cpp, ir/value.h, llvm_util/utils.cpp, tests/alive-tv/memory/alloca-malloc-fail.src.ll, tests/alive-tv/memory/alloca-malloc-fail.tgt.ll, tests/alive-tv/memory/alloca-malloc.src.ll, tests/alive-tv/memory/alloca-malloc.tgt.ll, tests/alive-tv/memory/glb-5.src.ll, tests/alive-tv/memory/glb-5.tgt.ll, tests/alive-tv/memory/glb-externconst.src.ll, tests/alive-tv/memory/glb-externconst.tgt.ll, tests/alive-tv/memory/memset-store-fail.src.ll, tests/alive-tv/memory/memset-store-fail.tgt.ll, tests/alive-tv/memory/memset-store.src.ll, tests/alive-tv/memory/memset-store.tgt.ll
This PR
- Makes storing to const global UB (by adding `blocks_readonly` array)
- Supports extern const globals (which do not have initial values)
- Adds a few more tests.
Unit tests: 152 -> 153 fails; the failure is llvm-test/Transforms/GlobalOpt/invariant.ll .
What it does is pretty interesting:
```
@object1 = global i32 0
define void @ctor1() {
store i32 -1, i32* @object1
%A = bitcast i32* @object1 to i8*
call void @test1(i8* %A)
ret void
}
```
=>
```
@object1 = constant i32 -1
define void @ctor1() local_unnamed_addr {
store i32 -1, i32* @object1
%A = bitcast i32* @object1 to i8*
call void @test1(i8* %A)
ret void
}
```
But I think this is wrong, because LLVM LangRef states that const global var can be placed at read-only section of an executable:
```
A variable may be defined as a …
```
=> Let storing to const globals UB, support extern const globals

CMakeLists.txt
=> add z3 library to alive-tv target

tools/alive-tv.cpp
do not check functions that contain zero instructions
=> do not check declarations

smt/expr.cpp, tests/unit/fshl/folds32.opt, tests/unit/fshr/folds32.opt
I was playing with the code and realized the existing encodings for funnel shifts times out in some cases for higher bits. The newly added file in this patch for funnel shift tests (same as folds.opt but with 32 bits inputs minus some timeout cases) times out in majority of the cases or takes more time with earlier encodings but works fine with this patch. 
It still takes takes time for simple transformations (for higher bits) involving a constant though. I have omitted those test cases from new fold32.opt. Not much idea why those are taking much time.
=> better encodings for funnel shifts

tools/alive-tv.cpp
transformation in the alive-tv summary output
=> disambiguate an alive problem (timeout, OOM, etc.) from an incorrect

ir/function.h, ir/memory.cpp, ir/memory.h, ir/state.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/memory/bigendian-fail.src.ll, tests/alive-tv/memory/bigendian-fail.tgt.ll, tests/alive-tv/memory/bigendian.src.ll, tests/alive-tv/memory/bigendian.tgt.ll, tests/alive-tv/memory/pre-bigendian.src.ll, tests/alive-tv/memory/pre-bigendian.tgt.ll, tools/alive-tv.cpp
This PR adds support for big endian. This PR is orthogonal with #149.
Interestingly `GVN/PRE/rle.ll` (which was mentioned in the #149) still raises `Target is more poisonous than source`, which seems to be related with a bug of alive-tv with undef, because alive-tv is printing that source and targets' values are both `poison`.
=> Support big endian

ir/function.cpp, ir/state.cpp, llvm_util/llvm2alive.cpp, llvm_util/utils.cpp
make sure this string appears in the output when something goes wrong, so that bulk alive2 runs can be quickly scanned for problems
=> try to more consistently include the string ERROR in errors

ir/memory.cpp, ir/memory.h
This patch changes arrays to UF if they are constant over program execution.
For example, `blks_kind` (which returns whether a memory block is defined at heap or not) has its value never changed after allocated, so it is moved to UF.
In contrary, `blks_liveness` may change during execution (e.g. `free(ptr)`), so it is kept as an array.
=> Declare blocks_kind / blocks_readonly as UF

tests/lit/lit/formats/alive2test.py
This PR updates alive2test.py so identical input tests (`alive-tv <input.ll> <input.ll>`) are run.
=> Let alive2test.py run same input check as well

tests/lit/lit/formats/alive2test.py
This resolves following Python error when running particular tests that are not pushed yet:
```
File "/Users/juneyounglee/alive2/tests/lit/lit/formats/alive2test.py", line 109, in execute
if string.find(err, xfail.group(1)) != -1:
AttributeError: 'NoneType' object has no attribute 'group'
```
=> Check that xfail is not none

llvm_util/llvm2alive.cpp, tests/alive-tv/memory/gep-struct1-fail.src.ll, tests/alive-tv/memory/gep-struct1-fail.tgt.ll, tests/alive-tv/memory/gep-struct1.src.ll, tests/alive-tv/memory/gep-struct1.tgt.ll, tests/alive-tv/memory/gep-struct2.src.ll, tests/alive-tv/memory/gep-struct2.tgt.ll
it's possible that i am overlooking something and there's more to it but following the code around, struct indexing should already work with following change. Can you point to any other issues, if any, that needs to be addressed for this?
=> add support for struct indexing

llvm_util/known_fns.cpp, llvm_util/known_fns.h, llvm_util/llvm2alive.cpp, llvm_util/utils.cpp, llvm_util/utils.h, tests/alive-tv/constexpr/loadgep-fail.src.ll, tests/alive-tv/constexpr/loadgep-fail.tgt.ll, tests/alive-tv/constexpr/loadgep.src.ll, tests/alive-tv/constexpr/loadgep.tgt.ll, tests/alive-tv/constexpr/phigep-fail.src.ll, tests/alive-tv/constexpr/phigep-fail.tgt.ll, tests/alive-tv/constexpr/phigep.src.ll, tests/alive-tv/constexpr/phigep.tgt.ll, tests/alive-tv/constexpr/ptrdiff.src.ll, tests/alive-tv/constexpr/ptrdiff.tgt.ll
This PR converts constexprs in a function to instructions. (#176)
This does not address initializers of global variables.
Interestingly, the # of unsupported getelementptrs at the report increased (about 2500 -> 3300). I guess the reason could be
(1) Most of constexpr geps are working on array types, which are not supported yet
(2) The gep operations which were not appearing at top 20 was now aggregated.
I think it will be great if someone can work on array types. Maybe @Dongjoo-Kim can help here.
The result of unsupported IR features change:
```
Unsupported IR features (Top 20):                                                                                                                                                                                                             
3430 …
```
=> Support constexprs (no initializer support yet)

ir/instr.cpp, ir/memory.cpp, ir/memory.h, tests/alive-tv/memory/calloc-init-fail.src.ll, tests/alive-tv/memory/calloc-init-fail.tgt.ll
Let calloc successfully initialize.
`Pointer::Pointer(const Memory &m, const char *var_name)` was creating a non-local pointer, and it was incorrectly used by Memory::memset.
Similar thing was happening in memcpy as well.
=> Fix a calloc bug

CMakeLists.txt
Previously, running cmake without re2c installed would print `-- RE2C: RE2C-NOTFOUND` and succeed, and then the build would fail due to trying to run an executable called 'RE2C-NOTFOUND'.
This pull request causes the cmake generation itself to fail, with a more obvious error message.
=> Fail on CMake generation if re2c not found

tests/alive-tv/memory/undefptr.src.ll, tests/alive-tv/memory/undefptr.tgt.ll, tools/transform.cpp
This PR addresses about 20 "Assertion `!memory_unused()' failed." error from LLVM unit tests.
nullptr_is_used should consider undef pointer because undef pointer is pointing to a null block.
=> nullptr_is_used should consider undef pointer too

llvm_util/llvm2alive.cpp, scripts/stats.php, tests/alive-tv/memory/gep-struct1-fail.src.ll, tests/alive-tv/memory/gep-struct1-fail.tgt.ll, tests/alive-tv/memory/gep-struct1.src.ll, tests/alive-tv/memory/gep-struct1.tgt.ll, tests/alive-tv/memory/gep-struct2.src.ll, tests/alive-tv/memory/gep-struct2.tgt.ll, tests/alive-tv/memory/memset-fn.tgt.ll
Function arguments' attributes were being ignored, causing verification failure.
Unit test failures: 242 -> 223.
Unsupported IR features: 
```
Unsupported IR features (Top 20):                                                                                                                                                                                                             
3324  getelementptr inbounds                                                                                                                                                                                                                  
2789  phi i32 …
```
=> Unsupport function argument attributes by default

tools/transform.cpp
This helps alive-tv/memory tests all pass (except `gep-struct2.src.ll`, which takes almost 1 second so the result is flaky)
=> Increment num_max_nonlocals_inst lesser

smt/expr.cpp
This simplifies extraction of malloc's bid, because malloc either returns null or local ptr, both of which are constants
=> Optimize (extract (ite _ const1 const2))

ir/function.cpp, ir/function.h, ir/memory.cpp, ir/state.h, llvm_util/llvm2alive.cpp, llvm_util/llvm2alive.h, llvm_util/utils.cpp, tests/alive-tv/constexpr/constgep-fail.src.ll, tests/alive-tv/constexpr/constgep-fail.tgt.ll, tests/alive-tv/constexpr/constgep.src.ll, tests/alive-tv/constexpr/constgep.tgt.ll, tests/alive-tv/constexpr/cycle.src.ll, tests/alive-tv/constexpr/cycle.tgt.ll, tests/alive-tv/globalopt.src.ll, tests/alive-tv/globalopt.tgt.ll, tests/alive-tv/memory/glb-1.src.ll, tests/alive-tv/memory/glb-align-fail.tgt.ll, tests/alive-tv/refinement/const-fail.src.ll, tests/alive-tv/refinement/const-fail.tgt.ll, tools/alive-tv.cpp, tv/tv.cpp, util/symexec.cpp
This PR creates a standalone basic block which is called "initializer block", and let llvm2alive.cpp add constexprs of initializers to it.
This patch helps LLVM's `Transforms/GlobalOpt/array-elem-refs.ll` pass.
The output of `alive-tv constgep.src.ll constgep.tgt.ll` looks like this:
```
{
__globalvars_init:
%__constexpr_0 = bitcast * @x to *
store * %__constexpr_0, * @y, align 1
}
define * @f() {
%0:
%p = load *, * @y, align 8
ret * %p
}
=>
{
__globalvars_init:
%__constexpr_1 = bitcast * @x to *
store * %__constexpr_1, * @y, align 1
}
define * @f() {
%0:
%p = load *, * @y, align 8
%a = bitcast * @x to *
%b = gep inbounds * %a, 1 x i64 0
ret * %b
}
Transformation seems to be correct!
```
=> Support constexprs in initializers

tests/alive-tv/dbg.src.ll, tests/alive-tv/dbg.tgt.ll, tests/lit/lit/formats/alive2test.py, tools/alive-tv.cpp, tools/transform.cpp, util/config.cpp, util/config.h
This is a patch that adds `-dbg` commandline flag to alive-tv, and add CHECK: grammar to lit
=> Add -dbg flag, add CHECK: test to lit

ir/state.cpp, ir/state.h, ir/value.cpp, tests/alive-tv/constexpr/aggregate2.src.ll, tests/alive-tv/constexpr/aggregate2.tgt.ll
This resolves issue #205.
GlobalVariable::toSMT() checks whether it is being called twice, and if it does, calls Memory::alloc() only once.
=> Fix assertion failure when GlobalVariable::toSMT is called twice in src

ir/type.cpp, ir/type.h, llvm_util/utils.cpp, tests/alive-tv/constexpr/string.src.ll, tests/alive-tv/constexpr/string.tgt.ll
This implements array type without paddings.
Unlike vector, array only has static number of elements.
Next I'll be working on array paddings. For example, [2 x i24] has paddings between elements.
Also I'll find fix for random failures in LLVM unit tests too.
=> Implement array (no padding)

tests/alive-tv/memory/ptrtoint-free-reorder-fail.src.ll, tests/alive-tv/memory/ptrtoint-free-reorder-fail.tgt.ll, tests/alive-tv/memory/ptrtoint-free-reorder.src.ll, tests/alive-tv/memory/ptrtoint-free-reorder.tgt.ll
This adds sanity checks for #171 .
Right now the `local_blk_addr.del` at Memory::free never happens unless the program has UB (malloc.is_local() is never true, and freeing alloca is UB), so just adding tests seems enough.
=> Add tests for reordering between ptrtoint & free

ir/type.cpp, ir/type.h, llvm_util/utils.cpp, tests/alive-tv/constexpr/zeroinitializer.src.ll, tests/alive-tv/constexpr/zeroinitializer.tgt.ll, tests/alive-tv/memory/array-gep.src.ll, tests/alive-tv/memory/array-gep.tgt.ll
This PR adds paddings after array elements if needed.
This helps these two tests pass: Transforms/SCCP/apint-array.ll , Transforms/SCCP/apint-bigint2.ll
There was no failure added.
=> Support array's padding

ir/instr.cpp, ir/type.cpp, ir/type.h, llvm_util/llvm2alive.cpp, tests/alive-tv/memory/gep-vector.src.ll, tests/alive-tv/memory/gep-vector.tgt.ll, tools/transform.cpp
This PR adds supports for gep with vector operands, and lets num_ptrinputs  include ptr elems in aggregates too. The reason is as follows:
```
define <2 x i8*> @f(<2 x i8*> %a) {
ret <2 x i8*> %a
}
=>
define <2 x i8*> @f(<2 x i8*> %a) {
ret <2 x i8*> %a
}
```
In this program, %a was not being counted into num_ptrinputs because it was aggregate, but there should have been at least one used memory block when getting formula for refinement of pointer.
To be conservative, I counted all pointer elements in aggregate operands' types as num_ptrinputs.
=> Support gep with vector operands, let num_ptrinputs count ptr elems in aggregates

tv/tv.cpp
the ```#if __GNUC__ < 8``` is no longer sufficient to make alive2 compile using LLVM 9 on OS X.
the fix below is certainly the wrong one, but I'm not certain what the right one is.
=> fix the build on Mac

scripts/opt-alive.sh
`extract-blocks` pass extracts specified blocks (from commandline arguments) as a distinct function and introduces calls.
ex: Transforms/BlockExtractor/extract-blocks.ll
=> Add extract-blocks to ignore list

llvm_util/utils.cpp, scripts/opt-alive.sh, tests/alive-tv/memory/aggregate-empty.src.ll, tests/alive-tv/memory/aggregate-empty.tgt.ll
- Fixes a crash regarding opaque type
- Adds a test for empty arrays
- Ignore `place-safepoints` because it is introducing function calls (`@do_safepoint`)
=> Fix a crash, add an empty array test, ignore place-safepoints pass

README.md
For normal day-to-day usage, `LLVM_BUILD_LLVM_DYLIB` may perhaps be a somewhat larger entry cost
as compared to the other prerequisites (RTTI+EH). It may be helpful to document
that `BUILD_SHARED_LIBS` (which is likely already enabled if one works on LLVM) is sufficient instead.
=> README.md: BUILD_SHARED_LIBS works inplace of LLVM_BUILD_LLVM_DYLIB

ir/instr.cpp, tests/alive-tv/memory/gep-vector.src.ll, tests/alive-tv/memory/gep-vector.tgt.ll
gep supports mixture of non-vector pointer and vector indices, e.g. `gep * %ptr, <2 x i64> <0, 1>`. This PR addresses the case.
=> Support the case when ptr is non-vector whereas idx has vectors

llvm_util/llvm2alive.cpp
Transforms/DeadStoreElimination/simple.ll has tests that exploit byval attributes, and alive-tv fails with the tests
=> Unsupport byval attribute

ir/memory.cpp, ir/memory.h, tests/alive-tv/memory/align.src.ll, tests/alive-tv/memory/align.tgt.ll
This fixes a bug of encoding of nonlocal pointer's alignments.
The original is_aligned was only checking block's alignment (using the `blk_align` array), and didn't consider offsets, which perhaps caused the confusion.
I renamed the original is_aligned to is_block_aligned & defined is_aligned to address this.
=> Fix a bug regarding nonlocal ptr's align

ir/memory.cpp, ir/memory.h, tests/alive-tv/memory/gep-struct2.src.ll, tests/alive-tv/memory/pre-bigendian.src.ll, tests/alive-tv/memory/punning-intptr.src.ll, tests/alive-tv/memory/punning-ptrint.src.ll, tests/alive-tv/memory/punning-ptrint.tgt.ll, tests/alive-tv/memory/store-removal.src.ll, tests/alive-tv/memory/store-removal.tgt.ll, tests/alive-tv/memory/zeroinit-memset.src.ll, tests/alive-tv/memory/zeroinit-memset.tgt.ll, tests/alive-tv/refinement/zero-null.src.ll, tests/alive-tv/refinement/zero-null.tgt.ll
This addresses #236 .
Reading null pointer byte as int yields 0, and zero int byte as pointer yields null pointer.
Further optimization can be done by redefining layout of a byte, so pointer value and int value can overlap.
=> Make null ptr byte and zero int byte compatible

ir/instr.cpp, ir/instr.h, ir/memory.cpp, ir/memory.h, llvm_util/llvm2alive.cpp
We cannot simply defer execution of alloca until lifetime.start() because operations like gep can use the pointer before lifefime.start.
```
void g(int*);
void f(int n) {
for (int i = 0; i < n; i++)
{ int q[2] = {i, i}; g(&q[1]); } // After -O3, `gep q, 1` is hoisted out of the loop
}
```
So, this PR adds StartLifetime instruction that explicitly states when the lifetime of the alloca begins.
In this PR, StartLifetime does nothing except it marks liveness of the variable as true.
The next PR will be making alloca initially dead if lifetime.start exists, and let execution of StartLifetime encode disjointness of local blocks as well.
=> Support lifetime.start (1/2)

ir/instr.cpp, ir/instr.h, ir/memory.cpp, ir/memory.h, llvm_util/llvm2alive.cpp, tests/alive-tv/memory/lifetime-2.src.ll, tests/alive-tv/memory/lifetime-2.tgt.ll, tests/alive-tv/memory/lifetime-noub.src.ll, tests/alive-tv/memory/lifetime-noub.tgt.ll
This adds encoding of  lifetime.end.
To finish lifetime of alloca, Free instruction with `unconstrained` parameter set as true is used.
It is allowed to give a pointer to alloca with non-zero offset, and I couldn't find an example that needs the double lifetime.end() call to be UB, so I named it as unconstrained.
(Note that it raises unsupported if non-alloca is given to lifetime.end)
=> Support lifetime.end

ir/memory.cpp
This is a pre-work to reduce the size of diff for the next lifetime.start PR.
Disjointness of local blocks is encoded by encodeDisjointnessOfLocalBlk.
Memory::start_lifetime() will use this function to encode disjointness too.
=> Define encodeDisjointnessOfLocalBlk for encoding disjointness of local blks

ir/instr.cpp, ir/instr.h, ir/memory.cpp, ir/memory.h, ir/value.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/memory/lifetime-2.src.ll, tests/alive-tv/memory/lifetime-2.tgt.ll, tests/alive-tv/memory/lifetime-reorder.src.ll, tests/alive-tv/memory/lifetime-reorder.tgt.ll
Key changes are:
1. Alloca now takes 'is_dead' bool. If it is true, the block's liveness is initially set as false. But, the alloca still returns a non-null pointer to allow using the alloca (e.g. bitcast, gep) before lifetime.start().
This involves updating Memory::alloc()'s return type as a pair of expr, which is <a pointer to the block, is allocated?>.
2. llvm2alive.cpp checks whether alloca has lifetime.start uses. If it has, is_dead is set as true.
3. Memory::start_lifetime encodes disjointness as well as updates memory usage, if lifetime is updated.
=> Support lifetime.start (2/2)

tests/alive-tv/memory/storeptr-fail-2.src.ll, tests/alive-tv/memory/storeptr-fail-2.tgt.ll
Adds a test that stores a pointer
The bug was introduced by 518afa575cb2accce2a9e13b1fcbf87746a6cdef but just fixed at 8549273e348f7c67b519b5d5e2b4bd7faf40ee3a
=> Add pointer store test

tools/alive-tv.cpp
This PR adds the -max-mem option to alive-tv which only existed for tv.
=> Add -max-mem to alive-tv

scripts/opt-alive.sh
Ignore -attributor , -functionattrs when running tv because they are interprocedural passes.
attributor (Attributor.cpp):
```
// This file implements an inter procedural pass that deduces and/or propagating
// attributes. This is done in an abstract interpretation style fixpoint
// iteration. See the Attributor.h file comment and the class descriptions in
// that file for more information.
```
functionattrs (FunctionAttrs.cpp):
```
/// This file implements interprocedural passes which walk the
/// call-graph deducing and/or propagating function attributes.
```
=> Ignore -attributor , -functionattrs

ir/instr.cpp, tests/alive-tv/memory/memset-large.src.ll, tests/alive-tv/memory/memset-large.tgt.ll
This PR makes memset raise UB if the size does not fit in the pointer size.
Before this patch, memset's size was truncated to bits_size_t. This causes optimization that reduces memset's size to raise when overflow could happen.
ex)
```
memset(p, 0, i128 0x0000...10000...) // after truncation, size is 0
*p = 1;
->
memset(p+1, 0, i128 0x0000..0FFFF...) // after truncation, size is FFFF...
*p = 1;
```
This resolves Transforms/MemCpyOpt/memset-memcpy-redundant-memset.ll 's `@test_different_types_i128_i32`.
=> Let memset raise UB if vbytes is larger than bits_size_t

tv/tv.cpp
Currently LLVM unit tests are run with `-tv-exit-on-error`, which hides succeeding tests after the first failure.
To run all tests, `-tv-exit-on-error` should be dropped, but it causes tv to report success to llvm-lit even if there was an incorrect optimization.
This PR resolves it. I think making tv explicitly fail is better because it allows tv to report any unit test having failure.
=> Report fatal error even if tv-exit-on-error is not given

ir/instr.cpp, ir/memory.cpp, ir/memory.h, ir/value.cpp, ir/value.h, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/nocapture.src.ll, tests/alive-tv/attrs/nocapture.tgt.ll
This is a PR for supporting nocapture attribute.
Fully supporting it requires significant job (and its semantics is not clear when poison is involved as discussed).
This patch is WIP; feel free to leave comments. I'll be back and update this soon.
Here is the list of sanity checks of nocapture that I think should be satisfied + sanity checks from LLVM's nocapture tests.
1.
```
define void @f(i8* nocapture %p) {
store %p, @glb // should be UB
}
```
2. 
```
define void @g(i8* nocapture %p, i8* %q) {
// p == q can happen unless noalias is given
store %q, @glb // should not be UB even if p == q.
}
```
3.
```
define void @g(i8* nocapture %ptr) {
ret ptr // UB. Transforms/Attributor/nocapture-2.ll
}
define void @g(i8* nocapture %ptr) {
ret (gep ptr, 1) // UB. …
```
=> Support nocapture

ir/globals.cpp, ir/globals.h, ir/instr.cpp, ir/memory.cpp, ir/memory.h, ir/type.cpp, ir/value.cpp, ir/value.h, llvm_util/llvm2alive.cpp, smt/expr.cpp, smt/expr.h, tests/alive-tv/attrs/nocapture-icmp.src.ll, tests/alive-tv/attrs/nocapture-icmp.tgt.ll, tests/alive-tv/attrs/nocapture-replace.src.ll, tests/alive-tv/attrs/nocapture-replace.tgt.ll, tests/alive-tv/attrs/nocapture.src.ll, tests/alive-tv/attrs/nocapture.tgt.ll, tools/transform.cpp
Splitted the diffs into two commits for easier review.
LLVM unit test failures: 63 -> 67
I think all 4 added failures are bugs in alive2 - 1 is the floating point bug, 3 are oggenc's DSE example. I'm investigating the reason.
```
Transforms/SLPVectorizer/X86/phi.ll: floating point bug
Transforms/DeadStoreElimination/OverwriteStoreBegin.ll
Transforms/DeadStoreElimination/OverwriteStoreEnd.ll
Transforms/MemCpyOpt/profitable-memset.ll
```
=> Add attribute bits to pointer & support nocapture

ir/instr.cpp, ir/state.cpp, ir/state.h, tests/alive-tv/memory/alloca-removal.src.ll, tests/alive-tv/memory/alloca-removal.tgt.ll
This helps the removal of alloca test work even when `-disable-undef-input` is not given, by registering the undef Z3 variables used by the size value.
=> Register undef variables used by the size argument of malloc

scripts/opt-alive.sh
metarenamer pass anonymizes function names, so function call does not match between source and target
=> Add -metarenamer to ignore list

tests/alive-tv/inttoptr.src.ll, tests/alive-tv/inttoptr.tgt.ll, tests/lit/lit/formats/alive2test.py
This helps adding a unit test for #270
=> Exclude invalid expr from identity test

ir/memory.cpp, tests/alive-tv/intptrload.src.ll, tests/alive-tv/intptrload.tgt.ll
Sanity check (this couldn't be added to unit test because src identity check should succeed):
```
define i64 @f(i64 %x, i64 %y) {
%p = inttoptr i64 %x to i64*
%a = load i64, i64* %p
ret i64 %a
}
=>
define i64 @f(i64 %x, i64 %y) {
unreachable
}
```
This example should raise `Invalid expr`.
=> Pointer::get_value should check validity of p

ir/memory.cpp
This happened when making observes_addresses() always return true
=> Fix a bug in Pointer::get_address

ir/state.cpp, tests/alive-tv/fncall-vararg.src.ll, tests/alive-tv/fncall-vararg.tgt.ll
This can happen when a function has variadic arguments.
=> Deal with the case when # args don't match

ir/instr.cpp, ir/state.cpp
Resolves failure when there are vararg fncalls with different types (e.g. `printf("%d", 10)`, `printf("%f", 0.1)`)
=> Address the case when fncall's vararg types are different

tests/lit/lit/formats/alive2test.py
I met #225 as well and turns out that the reason was incorrect string.find use at alive2test.py
=> Use Python3-compliant find

ir/instr.cpp, ir/value.cpp, tests/alive-tv/vector_undefptr.src.ll, tests/alive-tv/vector_undefptr.tgt.ll
This PR adds constraint to undef aggregate value's pointer elements so they have correct values.
=> Let GEP's ptr duplicate undef vars when idx is a vector type

ir/instr.cpp
This PR makes memcpy raise UB if it receives its size larger than 64 bits.
It resolves failure of unit test `Transforms/MemCpyOpt/memset-memcpy-redundant-memset.ll`, `test_different_types_i32_i128()`.
=> Raise UB when memcpy receives size larger than 64 bits

ir/globals.cpp, ir/globals.h, ir/memory.cpp, ir/memory.h, ir/value.cpp, ir/value.h, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/readnone-fail.src.ll, tests/alive-tv/attrs/readnone-fail.tgt.ll, tests/alive-tv/attrs/readnone.src.ll, tests/alive-tv/attrs/readnone.tgt.ll, tools/transform.cpp
This PR adds support for readnone attribute of arguments.
Three failures appear:
```
Transforms/InstCombine/gep-combine-loop-invariant.ll
Transforms/InstCombine/select-cmp-br.ll
Transforms/LoopUnswitch/2007-08-01-LCSSA.ll
```
The first one is the bug regarding gep inbounds.
The second one is about the semantics of or i1, the third one is loop unswitch.
=> Support readnone arg attribute

README.md, tv/CMakeLists.txt, tv/tv.cpp
This is a patch that let alive2 run as a clang plugin.
It uses the new pass manager to get callback after each pass. It seems the new pass manager is working pretty well.
To make this PR work, https://reviews.llvm.org/D71086 needs to be reviewed. It is adding just a couple of lines to LLVM's header.
```
clang -fpass-plugin=build/tv/tv.dylib -fexperimental-new-pass-manager -O3 a.c -S -emit-llvm \
-Xclang -load -Xclang tv/tv.dylib
```
You can give additional arguments with -mllvm (e.g. -mllvm -tv-smt-to=2000)
=> Support clang plugin

ir/instr.cpp, ir/instr.h, llvm_util/known_fns.cpp, tests/alive-tv/memory/realloc-fail.src.ll, tests/alive-tv/memory/realloc-fail.tgt.ll, tests/alive-tv/memory/realloc-null.src.ll, tests/alive-tv/memory/realloc-null.tgt.ll, tests/alive-tv/memory/realloc-zero.src.ll, tests/alive-tv/memory/realloc-zero.tgt.ll, tests/alive-tv/memory/realloc.src.ll, tests/alive-tv/memory/realloc.tgt.ll, tools/alive_parser.cpp, tools/transform.cpp
I added realloc instruction.
Realloc is implemented using malloc, memcpy and free.
First, allocate pointer with the size.
If the allocation is success, copy the previous pointer's value to new pointer and free it.
If not, preserve the previous pointer.
However, there is one restriction.
In this implementation, allocation is run before free.
So, the result of realloc is always disjoint with the previous one.
If free precede allocation, then memcpy isn't available.
Could you help me in this matter?
=> add realloc

CMakeLists.txt, README.md, tools/alive-tv.cpp
- after a CMake update (on Ubuntu 18.04) we now need to explicitly find ZLIB
- some improvements to alive-tv's help output: a more detailed
summary, removed "Alive:" from in front of the help text since our
options are clearly in the alive option category, and tell the
command line library to hide all unrelated command line options
- support running alive-tv with just a single file, in which case
we run opt -O2 on it and verify refinment of that
=> a few changes, the main one is to allow people to verify an optimization without trying to remember the tricky "opt" invocation

CMakeLists.txt
llvm::CloneModule() is used by alive-tv, but we don't explicitly
link to the library that provides it, but only implicitly.
And even after purging alive2 build dir, with local llvm trunk being at
https://github.com/llvm/llvm-project/commit/857b655d7aac50462ffd0154b9d6c4f18119ddfb
i can no longer successfully build alive2:
```
[62/65] Linking CXX executable alive-tv
FAILED: alive-tv
: && /usr/local/bin/clang++  -Wall -Werror -march=native -fPIC -flto=thin -fuse-ld=lld -Wno-error=unused-command-line-argument -O3 -DNDEBUG -O3 -DNDEBUG  -Wl,-O3 -Wl,--gc-sections CMakeFiles/alive-tv.dir/tools/alive-tv.cpp.o  -o alive-tv  -Wl,-rpath,"\$ORIGIN/../lib:/builddirs/llvm-project/build-Clang9-unknown/./lib"  -lpthread  libllvm_util.a  libir.a  libsmt.a  libtools.a  libutil.a …
```
=> [TV] Do explicitly link to LLVMTransformUtils that provides llvm::CloneModule()

tools/alive-tv.cpp
I feel like "errors" could be confusing to people
=> clarify what 'errors' means in alive-tv output

tests/alive-tv/call.src.ll, tests/alive-tv/call.tgt.ll, util/symexec.cpp
finishInitializer() is called too late, causing the Memory::initial_non_local_block_val of the next basic block to be uninitialized.
This resolves 50 invalid expr errors from LLVM unit tests.
=> Call finishInitializer before jump is called

tests/README.md, tests/alive-tv/easy-1.srctgt.ll, tests/alive-tv/easy-2.srctgt.ll, tests/lit/lit/formats/alive2test.py, tools/alive-tv.cpp
convenient from compiler explorer
if alive-tv is handed a single file and it contains a function called
src and a function called tgt, then check refinment of that
also, add a new test mode for single files, and document our test formats
in a README.md file in the tests directory
=> this adds another mode for using alive-tv that is intended to be

ir/instr.cpp, ir/instr.h, ir/memory.cpp, ir/memory.h, ir/state.cpp, ir/state.h, llvm_util/llvm2alive.cpp, tests/alive-tv/call.src.ll, tests/alive-tv/call.tgt.ll, tools/alive_parser.cpp
This PR deal with the case when the callee's pointer argument has byval attribute.
```
define i8 @f6_2(i8* %p) {
%a = alloca i8
call void @llvm.memcpy.p0i8.p0i8.i64(i8* %a, i8* %p, i64 1, i1 false)
%b = call i8 @g2(i8* byval %a)
ret i8 %b
}
declare i8 @g2(i8* byval)
=>
define i8 @f6_2(i8* %p) {
%b = call i8 @g2(i8* byval %p)
ret i8 %b
}
```
=> Support the case when callee's attribute has byval

tools/alive-tv.cpp
This resolves an error that appears on my machine when running a srctgt test:
```
libc++abi.dylib: Pure virtual function called!
Abort trap: 6
```
=> Call smt_initializer::reset before exiting alive-tv

ir/memory.cpp, ir/memory.h
This PR makes raw load/ptrtoint/inttoptr const methods.
inttoptr is marked as const as well because it does not change memory according to the twin memory model.
=> Make several memory operations const

ir/instr.cpp, ir/memory.cpp, ir/memory.h, ir/state.cpp, ir/state.h
As discussed at #298, this PR makes Pointer::is_dereferenceable and Memory::load return UB constraints rather than directly updating State.
=> Let Pointer::is_dereferenceable and Memory::load return UB constraints

CMakeLists.txt, tests/lit/lit/formats/alive2test.py, tools/alive-tv.cpp
- make sure we ask CMake to look for ZLIB (I thought this was changed,
did we lose it somehow? anyway, this is mandatory now)
- optionally, send all alive-tv output to a file (this is for Compiler
Explorer, which sometimes wants to directly exec() our program
without going through a shell, so redirection doesn't work)
- only return a non-zero process exit code when there's actually an
error; don't consider TV failure to be an error. again this is mainly
to make Compiler Explorer happy: we don't want it to think our tool
crashed when there's a TV failure
=> this makes three changes to alive-tv:

tools/alive-tv.cpp
nuno your slight rewrite of my code crashes like this:
```
regehr@john-home:~/alive2/build$ ./alive-tv foo.ll  -o bla
pure virtual method called
terminate called without an active exception
Aborted
regehr@john-home:~/alive2/build$ 
```
=> fix crash when sending output to file

tools/alive-tv.cpp
I had thought it was a good idea to send stderr to the -o file, but this prevents compiler explorer from showing these error messages to users. this change seems to give the desired behavior.
=> it was a mistake to redirect stderr using the -o flag, so undo that

CMakeLists.txt
Adds `-DTEST_NTHREADS=..` to cmake.
This is helpful for reducing timeout failures by giving small number of cores.
Also this adds alive-tv to `ninja check`'s dependency
=> Add -DTEST_NTHREADS, put alive-tv as check's dependency

ir/instr.cpp, ir/instr.h, ir/state.cpp, ir/state.h, llvm_util/llvm2alive.cpp, tests/alive-tv/returned-fail.srctgt.ll, tests/alive-tv/returned.src.ll, tests/alive-tv/returned.tgt.ll
This PR adds support for returned attributes.
Resolves failure of:
```
Transforms/InstCombine/call.ll
Transforms/InstCombine/expensive-combines.ll
Transforms/InstCombine/pr44541.ll
Transforms/InstSimplify/returned.ll
```
=> Support returned

llvm_util/llvm2alive.cpp, tests/alive-tv/memory/glb-weak-fail.srctgt.ll
Deal with the case that was mentioned at #311
=> Store to constant global only when it has definitive initializer

ir/memory.cpp, tests/alive-tv/memory/ptr-cmp.src.ll
According to the twin memory sem, it returns a nondeterministic value.
This patch resolves 3 failures from LLVM unit tests:
```
Transforms/LoopLoadElim/forward.ll
Transforms/LoopLoadElim/memcheck.ll
Transforms/LoopLoadElim/opt-size.ll
```
=> Let ptr cmp ule/ult/.. with difference provenance return nondet value

tests/alive-tv/failcheck.src.ll, tests/alive-tv/failcheck.tgt.ll, tests/lit/lit/formats/alive2test.py
This also updates XFAIL to check stdout too.
Realized that we were missing several fails, including alive-tv/memory/lifetime-1.src.ll ; it was raising `Precondition is false` error.
=> alive2test.py should check absence of 'ERROR: ..' too

ir/memory.cpp
There was a bug at mk_nonlocal_val_axioms() that makes axiom to be always false when num_nonlocals == 0, causing some unit tests to raise `precondition is false` error
```
Byte byte(m, val.load(idx));
Pointer loadedptr = byte.ptr();
expr bid = loadedptr.get_short_bid();
s.addAxiom(
expr::mkForAll({ idx },
byte.is_ptr().implies(
!loadedptr.is_local() && // << this was always false
!loadedptr.is_nocapture() &&
bid.ule(m.num_nonlocals() - 1))));
```
=> mk_nonlocal_val_axioms should do nothing when num_nonlocals == 0

llvm_util/llvm2alive.cpp, scripts/stats.php
This is especially helpful when e.g. a long string constant is used
=> Raise Unsupported constant error if glbvar's initializer cannot be translated

tests/alive-tv/params/succinct-correct.srctgt.ll, tests/alive-tv/params/succinct-incorrect.srctgt.ll, tests/lit/lit/formats/alive2test.py, tools/alive-tv.cpp
This adds --succinct param to alive-tv.
With this flag enabled, alive-tv prints a single line per function.
This helps reduce the size of logs emitted from TV.
To add tests for --succinct, I added CHECK-NOT: predicate.
This required small rewrites to ailve2test.py , because CHECK-NOT should succeed regardless of whether the transformation is correct or not.
=> Add --succinct param to alive-tv, add CHECK-NOT directive

ir/function.cpp, ir/function.h, tv/tv.cpp
This should correctly build dominator trees and print them as .dot files. The main use is to be able to lookup for the dominators or immediate dominator of a given node in O(1). I experimented with building an edge_iterator for it but that would require creating a second map with the relationship dominator->dominated nodes just for iterating over edges. At the moment i don't see any use for this other than quick immediate dominator lookup.
=> Implement dominator tree

tests/alive-tv/memory/memcpy-3-loadstore.srctgt.ll, tools/transform.cpp
.. because load i8 yields poison if it was a pointer byte.
This implies that we don't have 'unsigned char' type in the twin memory model right now.
To recap: making i8 as unsigned char again causes all arithmetic optimizations on i8  unsound/controversial again, so this was our design choice.
=> Let memcpy -> load/store i8 raise memory mismatch

tests/alive-tv/bitcast/bitcast-vector-bigendian.src.ll, tests/alive-tv/bitcast/bitcast-vector-bigendian.tgt.ll, tests/alive-tv/bitcast/bitcast-vector.src.ll, tests/alive-tv/bitcast/bitcast-vector.tgt.ll, tests/alive-tv/bitcast/cast-vec-roundtrip-bigendian.srctgt.ll, tests/alive-tv/bitcast/cast-vec-roundtrip.srctgt.ll, tests/alive-tv/bitcast/vec-cast-roundtrip-bigendian.srctgt.ll, tests/alive-tv/bitcast/vec-cast-roundtrip.srctgt.ll
I'm attacking #277 now, and these are sanity checks for correct semantics of bitcasts
=> Add tests for bitcast between int and vector

ir/memory.cpp, ir/type.cpp, ir/type.h, tests/alive-tv/memory/vectors-float.srctgt.ll, tests/alive-tv/memory/vectors-i12.srctgt.ll, tests/alive-tv/memory/vectors-small-bigendian-fail.srctgt.ll, tests/alive-tv/memory/vectors-small-bigendian.src.ll, tests/alive-tv/memory/vectors-small-bigendian.tgt.ll, tests/alive-tv/memory/vectors-small-fail.srctgt.ll, tests/alive-tv/memory/vectors-small.src.ll, tests/alive-tv/memory/vectors-small.tgt.ll
This resolves #277 by making int vectors be encoded as primitive values at valueToBytes / bytesToValue.
For structs (e.g. {i1, ..}), this doesn't work, because each element occupy its own byte.
Fixes one failure (Transforms/SROA/vector-promotion-different-size.ll).
=> Support vector load/store with element size not a multiple of 8

ir/type.cpp, tests/alive-tv/insertvalue-emptyelem.srctgt.ll
This resolves assertion failure from Transforms/SROA/basictest.ll
=> Let AggregateType::extract return an empty statevalue if children[idx]'s bit == 0

tests/alive-tv/bugs/pr43948.srctgt.ll
.. because it raises timeout on my machine. :/
I have a feeling that Z3 in Mac is slower than in Linux machines.
=> Increase timeout of pr43948.srctgt.ll

ir/instr.cpp, ir/type.cpp, ir/type.h, tests/alive-tv/memory/umul_overflow-fail.srctgt.ll, tests/alive-tv/memory/umul_overflow.srctgt.ll, tests/alive-tv/sadd_overflow.srctgt.ll, tests/alive-tv/sadd_overflow_vec.srctgt.ll, tests/alive-tv/umul_overflow.srctgt.ll
`tests/alive-tv/umul_overflow.srctgt.ll` raises type checking failure, and the reason is that in Alive2 umul_overflow's return type is not {i32, i1}, but {i32, i1, i24} because llvm2alive automatically inserts paddings.
This resolves this issue by inserting dummy values at such padding when encoding the result of umul_overflow.
This resolves type checking failures at LLVM unit tests & gzip single file benchmarks.
Exact numbers for LLVM unit tests - I'm running the tests
=> AggregateType maintains padding elements, and *_overflow should consider this too

ir/instr.cpp, tests/alive-tv/select-aggregate.srctgt.ll
This resolves at least one type check failure (InstCombine/cast.ll).
=> Select can return an aggregate value

ir/instr.cpp, ir/memory.cpp, ir/memory.h, ir/state.cpp, ir/type.cpp
This PR makes classes in Memory.h use camel case for member functions.
All classes in the ir/ directory except those are already using camel cases, so I think it is natural to use the convention in them as well.
=> Let Memory-related class use camel case for names of member functions

llvm_util/utils.cpp, tools/alive-tv.cpp
Since https://reviews.llvm.org/D77587 / https://github.com/llvm/llvm-project/commit/2dea3f129878e929e5d1f00b91a622eb1ec8be4e
Do we need to somehow uglify this to make building with older LLVM still possible?
=> Fix build with llvm trunk - llvm::Type::VectorTyID is now FixedVectorTyID

llvm_util/llvm2alive.cpp
Vector related API is rapidly changing.. :/
Fixes a build error that was introduced after https://reviews.llvm.org/D77690 landed
=> Fix a build error by using isa<llvm::ScalableVectorType> instead of isScalable()

ir/instr.cpp
Alive2 is printing the return type of fcmp at the place where operand type should be printed:
```
%c = fcmp oeq i1 %x, %x
```
This patch fixes it.
=> Let fcmp correctly print its operand type

ir/memory.cpp
https://github.com/AliveToolkit/alive2/pull/313 changed Pointer::slt/sle/.. to return nondeterministic result when pointers to different blocks are given.
This affected how ptr_deref_within works, which only needs the comparison between offsets because equality of block ids are compared separately.
This patch brings performance improvement by not using the Pointer::slt/slt/.., hence not introducing a quantified variable.
LLVM unit tests timeout: 1083 -> 1073
=> ptr_deref_within does not need nondeterministic comparison

ir/globals.cpp, ir/globals.h, ir/memory.cpp, ir/state.cpp, tests/alive-tv/opt-memory/has_null_block-2.srctgt.ll, tests/alive-tv/opt-memory/has_null_block-3.srctgt.ll, tests/alive-tv/opt-memory/has_null_block-4.srctgt.ll, tests/alive-tv/opt-memory/has_null_block-5.srctgt.ll, tests/alive-tv/opt-memory/has_null_block.srctgt.ll, tools/transform.cpp
Use non-local bid 0 as a plain block id if there is no null block.
I added has_null_block which represents whether either src or tgt needs the existence of the null block.
=> Use non-local bid 0 as a plain block id if there is no null block

ir/globals.cpp, ir/globals.h, ir/instr.cpp, ir/instr.h, llvm_util/known_fns.cpp, tests/alive-tv/memory/bcmp-identity.srctgt.ll, tests/alive-tv/memory/memcmp-basic-fail-2.srctgt.ll, tests/alive-tv/memory/memcmp-basic-fail-3.srctgt.ll, tests/alive-tv/memory/memcmp-basic-fail.srctgt.ll, tests/alive-tv/memory/memcmp-basic.src.ll, tests/alive-tv/memory/memcmp-basic.tgt.ll, tests/alive-tv/memory/memcmp-bcmp.srctgt.ll, tests/alive-tv/memory/memcmp-identity.srctgt.ll, tests/alive-tv/memory/memcmp-noub.srctgt.ll, tests/alive-tv/memory/memcmp-opt-bigendian.srctgt.ll, tests/alive-tv/memory/memcmp-opt-littleendian-fail.srctgt.ll, tests/alive-tv/memory/memcmp-ub.src.ll, tests/alive-tv/memory/memcmp-ub.tgt.ll, tools/transform.cpp
This implements memcmp/bcmp by manually unrolling comparisons `memcmp_unroll_cnt` times.
This only considers integer bytes (otherwise poison), but it already seems to work quite well for LLVM unit tests.
Has one regression from unit tests: Transforms/ExpandMemCmp/X86/memcmp.ll due to this kind of transformation:
```
define i32 @cmp2(* nocapture readonly %x, * nocapture readonly %y) {                
%0:                                                                                 
%call = memcmp * nocapture readonly %x, * nocapture readonly %y, i64 2            
ret i32 %call                                                                     
}                                                                                   
=> …
```
=> Implement memcmp/bcmp

ir/instr.cpp, tests/alive-tv/memory/memcmp-zero.srctgt.ll
According to man page, memcmp(p, q, 0) is defined as zero: http://man7.org/linux/man-pages/man3/memcmp.3.html .
Another fix is that the next iteration condition of memcmp was incorrectly defined; it should compare i+1 < n. For example, if n == 1, there should be no second iteration (i = 0 should be the last one). This resolves two regressions (Transforms/InstCombine/bcmp-1.ll , Transforms/InstCombine/memcmp-1.ll ).
=> Define memcmp(p,q,0) as zero, fix the last iteration condition

ir/memory.cpp, ir/memory.h
This resolves the stack overflow error on some large input bitcode pairs:
[overflow.zip](https://github.com/AliveToolkit/alive2/files/4602945/overflow.zip)
The reason was as follows:
(1) non_local_blk_nonwritable is a vector of bids
(2) Memory::mkIf merges two non_local_blk_nonwritable s without pruning out duplicated bids, causing exponential growth
(3) Pointer::isWritable does `non_local &= this_bid != bid` for each bid in non_local_blk_nonwritable
(4) AndExpr::add, which is called by Pointer::isDereferenceable, raises stack overflow when the expression creatd from Pointer::isWritable is given.
By defining non_local_blk_nonwritable as set instead, step (2) isn't happening anymore.
=> Use set for non_local_blk_nonwritable to prune out duplicated bids

ir/instr.cpp
This resolves the two regressions from LLVM unit tests.
=> Fix continue condition of memcmp to compare i+2 and n

ir/attrs.h, ir/instr.cpp, ir/instr.h, ir/memory.cpp, ir/memory.h, ir/type.cpp, ir/type.h, ir/value.cpp, ir/value.h, llvm_util/llvm2alive.cpp, tools/alive_parser.cpp, tools/transform.cpp
Before working on dereferenceable attributes, this factors out attributes as an independent class, because dereferenceable carries additional information (the num of bytes) which cannot be simply encoded as a bit.
=> Factor out attributes as an independent class

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/state.cpp, ir/state.h, ir/value.cpp, ir/value.h, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/dereferenceable-callsite-max.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fail.srctgt.ll, tests/alive-tv/attrs/dereferenceable.srctgt.ll, tests/alive-tv/opt-memory/dereferenceable.srctgt.ll, tools/transform.cpp
This PR adds support for dereferenceable attribute at function parameters.
Dereferenceable for function's return value isn't included because it requires factoring out function attributes as a class, which will make the diff big.
LLVM unit tests: two failures added;
```
Transforms/MergeICmps/X86/entry-block-shuffled.ll
Transforms/MergeICmps/X86/multiple-blocks-does-work.ll
```
The first one does `if (x) { if (y) { ... } }` -> `if (y) { if (x) { ... } }` which is illegal because it may introduce UB.
The second one is related with memcmp's semantics; Currently, memcmp raises UB if poison bytes are compared, but this requires memcmp to return poison...
=> Support dereferenceable attribute

ir/instr.cpp, tests/alive-tv/memory/memcmp-noub2.srctgt.ll, tests/alive-tv/memory/memcmp-noub3.srctgt.ll, tests/alive-tv/memory/memcmp-noub4.srctgt.ll, tests/alive-tv/memory/memcmp-ub.src.ll, tests/alive-tv/memory/memcmp-ub.tgt.ll
This fixes Transforms/MergeICmps/X86/multiple-blocks-does-work.ll .
=> Let memcmp return poison when comparing poisonous bytes

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/dereferenceable-ret-callsite.srctgt.ll, tests/alive-tv/attrs/dereferenceable-ret-callsite2.srctgt.ll
This PR adds support for dereferenceable attribute at a return value of a call.
=> Support dereferenceable attribute at the returned value

ir/memory.cpp, tests/alive-tv/memory/calloc-overflow.srctgt.ll, tests/alive-tv/memory/calloc-overflow.srctgt2.ll, tests/alive-tv/memory/calloc-overflow.tgt.ll
Without this fix, tests/alive-tv/memory/calloc-overflow.srctgt2.ll  raises precondition is false error.
=> Fix calloc's precondition is false error

ir/function.cpp, ir/function.h, ir/globals.cpp, ir/globals.h, ir/instr.cpp, ir/memory.cpp, ir/memory.h, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/dereferenceable-fndef-global.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef-global2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef-heap.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef-heap2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef-heap3.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef-null.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef-stack.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef3.srctgt.ll, tools/transform.cpp
This adds support for dereferenceable attribute in function definition (#384).
=> Add support for dereferenceable attribute in function definition

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/value.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/nonnull-callsite.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite2.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite3.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite4.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite5.srctgt.ll, tests/alive-tv/attrs/nonnull-fndef.srctgt.ll, tests/alive-tv/attrs/nonnull-fndef2.srctgt.ll, tests/alive-tv/attrs/nonnull-ret-callsite.srctgt.ll
This adds support for nonnull attribute.
Resolves two failures:
```
Transforms/CorrelatedValuePropagation/basic.ll
Transforms/InstSimplify/compare.ll
```
This encodes  f(nonnull poison) as UB, because poison can be folded into null, making f(nonnull null), which is UB. 
Relevant issue: https://github.com/AliveToolkit/alive2/issues/289
There was a relevant thread in llvm-dev in the past, too.
This semantics may not explain a few existing optimizations. For example, we cannot say 'gep inbounds p, 1' is non-null.
But I think it is better to unsupport a few optimizations than breaking the general refinement from poison to a concrete value at this point...
=> Add support for nonnull attribute

tests/unit/call-error6.opt, tools/alive_parser.cpp
I observed that `tests/unit/call-error6.opt` was printing `assume` and `assume_non_poison` in an inversed way, so I wonder whether the bool flag that is given to parse_assume should have been inversed.
With this fix, call-error6 successfully raises an error. call-error5 still passes silently, but this will be addressed in the other patch.
=> Fix the bool flag value given to parse_assume

tests/alive-tv/skip-smt.srctgt.ll, tools/alive-tv.cpp
Sorry for piling so many pull requests. :)
This adds -skip-smt to alive-tv, which already existed in alive binary.
Using this option, I'm going to see how long it takes to preprocess single file benchmarks.
=> Add -skip-smt option to alive-tv

ir/instr.cpp, ir/memory.cpp, ir/memory.h, ir/state.cpp, ir/state.h
To resolve https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=4beb2b117e2fdd2c&test=Transforms%2FSink%2Fcall.ll in the future, ptr_inputs should have readonly flag too (currently it only has byval, and ptr_input is represented as a pair of StateValue and bool).
This PR factors out it as a Memory::PtrInput so it will have more fields like byval, readonly, etc.
Also, I put a few assertions into State's methods which should fail if current_bb was not set.
=> Factor out Memory::PtrInput class, put assertions in State's methods

ir/instr.h, tools/transform.cpp
This is from #392 , with analysis-related part only.
There was a missing initialization for has_alloca/has_dead_allocas.
Also, may_be_nonlocal wasn't looking through select.
=> Initialize has_alloca/has_dead_allocas, let may_be_nonlocal see select

ir/state.cpp, tests/alive-tv/call.src.ll, tests/alive-tv/call.tgt.ll, tests/unit/call-error5.opt, tests/unit/call-error6.opt
This patch removes introduction of quantified variables that were created for encoding the return values of functions when poisons were given as inputs. 
No regressions in Alive2 unit tests & LLVM unit tests
LLVM unit tests' timeout #: 836 -> 817
=> Encode call site refinement without using quantified variables

tests/alive-tv/refinement/nondet-fail.srctgt.ll, tests/alive-tv/refinement/nondet-fail2.srctgt.ll, tools/transform.cpp
This resolves issue #385 , which happened because there was no entanglement between refinement of return value and refinement of final memory.
As the refinement formula becomes more complex, this causes slowdown in some cases; I added has_nondet_op which checks whether there is an operation that returns a nondeterministic value. If there is no nondet op, there is only a single execution given an input, so entanglement between the return value and final memory isn't needed.
Running LLVM unit tests...
=> Memory and value refinement should be checked together if there's nondet. exec.

tests/alive-tv/attrs/dereferenceable2.srctgt.ll, tools/transform.cpp
This is a simple patch that resolves `precondition is false` error that happens when a dereferenceable attribute is used with a big alignment.
=> Dereferenceable attr should update max_access_size

README.md
If CMake is not found, `Z3_LIBRARIES` also needs to be set along with `Z3_INCLUDE_DIR`. If not, configure and build fails.
=> Missing option for CMake

tv/tv.cpp
After https://reviews.llvm.org/D80692 / https://github.com/llvm/llvm-project/commit/1285e8bcac2c54ddd924ffb813b2b187467ac2a6
`registerOptimizerLastEPCallback()` expects `ModulePassManager`,
not `FunctionPassManager`, so a workaround/update is needed.
=> Fix clang-tv build with latest LLVM

CMakeLists.txt
so forever I have not been able to get alive2 to find libz3.so (at runtime, not cmake time) unless that library is in a standard location like /usr/lib. recently I had to fix similar issues in souper, so figured I'd fix them here as well. this tells CMake to set the RPATH of build products so that libraries can be found at runtime.
=> set build RPATH so we can find z3 in non-standard locations

smt/exprs.cpp
This reduces the time of a few oggenc's function pairs' preprocessing, from more than one hour to less than one minute.
=> Add a simplification rule to DisjointExpr

scripts/perf-testing/README.md, scripts/perf-testing/negative/add-to-shift1.ll, scripts/perf-testing/negative/add-to-shift2.ll, scripts/perf-testing/negative/ctpop1.ll, scripts/perf-testing/negative/ctpop2.ll, scripts/perf-testing/negative/ctpop3.ll, scripts/perf-testing/negative/demorgan1.ll, scripts/perf-testing/negative/demorgan2.ll, scripts/perf-testing/negative/sdiv1.ll, scripts/perf-testing/negative/udiv1.ll, scripts/perf-testing/positive/add-to-shift1.ll, scripts/perf-testing/positive/add-to-shift2.ll, scripts/perf-testing/positive/ctpop1.ll, scripts/perf-testing/positive/ctpop2.ll, scripts/perf-testing/positive/ctpop3.ll, scripts/perf-testing/positive/demorgan1.ll, scripts/perf-testing/positive/demorgan2.ll, scripts/perf-testing/positive/sdiv1.ll, scripts/perf-testing/positive/udiv1.ll, scripts/perf-testing/test.pl
a collection of tests that are parameterized by an integer value, and
tries them with increasing values until failure
Nuno, can you tolerate a standalone perl program like this? I volunteer to support it indefinitely.
example:
```
$ ./test.pl 
found 9 positive tests.
positive/add-to-shift1.ll : 12
positive/add-to-shift2.ll : 12
positive/ctpop1.ll : 12
positive/ctpop2.ll : 46
positive/ctpop3.ll : 48
positive/demorgan1.ll : 256
positive/demorgan2.ll : 9
positive/sdiv1.ll : 12
positive/udiv1.ll : 256
found 9 negative tests.
negative/add-to-shift1.ll : 256
negative/add-to-shift2.ll : 256
negative/ctpop1.ll : 16
negative/ctpop2.ll : 50
negative/ctpop3.ll : 65
negative/demorgan1.ll : 256
negative/demorgan2.ll : 256
negative/sdiv1.ll : 38
negative/udiv1.ll : 117
average score: 109.6
$
```
=> a simple test harness for checking scalability of alive; it comes with

ir/type.cpp, tests/alive-tv/refinement/ptr-returnmemory.srctgt.ll
PtrType::refines should use returnMemory().
Found this bug while investigating https://github.com/AliveToolkit/alive2/issues/412#issuecomment-640274035
Running LLVM unit tests to see its impact
=> PtrType::refines should use returnMemory()

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/memory.cpp, ir/memory.h, ir/state.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/dereferenceable-callsite-fail.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite-max.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-nofree.srctgt.ll, tests/alive-tv/attrs/nofree.srctgt.ll, tools/transform.cpp
This addresses #412.
Running this with LLVM unit test raises two failures, but this seems to be a pre-existing bug in Alive2. I'll write down the details at #412.
=> Add nofree attribute

ir/function.cpp, ir/function.h
The algorithm originally implemented by Cooper, Keith D.; Harvey, Timothy J.; and Kennedy, Ken (2001) in the paper http://www.cs.rice.edu/~keith/EMBED/dom.pdf had a flaw in which they assumed that two different basic blocks always have a common parent which is not the case when dead code exists.
I only made a couple of changes to the algorithm added in the pull request https://github.com/AliveToolkit/alive2/pull/304 such that dominator trees for bb's that have paths to them from program entry are correct, however it is not possible to guarantee the same for the bbs that are not reachable from program entry. This should not affect the ub algorithm in https://github.com/AliveToolkit/alive2/pull/369.
The main changes are ignoring back-edges, making sure that every block without predecessors …
=> Fix and extend dominators algorithm in function.h to support multi-root CFGs

scripts/perf-testing/negative/memcpy1.ll, scripts/perf-testing/negative/memcpy2.ll, scripts/perf-testing/negative/memcpy3.ll, scripts/perf-testing/negative/memcpy4.ll, scripts/perf-testing/negative/memcpy5.ll, scripts/perf-testing/negative/memcpy6.ll, scripts/perf-testing/positive/memcpy1.ll, scripts/perf-testing/positive/memcpy2.ll, scripts/perf-testing/positive/memcpy3.ll, scripts/perf-testing/positive/memcpy4.ll, scripts/perf-testing/positive/memcpy5.ll, scripts/perf-testing/positive/memcpy6.ll, scripts/perf-testing/test.pl
not sure these are great, since mostly the new memory tests either fail at 11 (falling off the unroll limit of 10, I guess) or go all the way to 256. I'd be happy for feedback from Juneyoung or Nuno
=> add memory model tests; these are parameterized by block size, not bitwidth

llvm_util/known_fns.cpp, scripts/opt-alive.sh, tests/alive-tv/printf.srctgt.ll, tools/alive-tv.cpp, tv/tv.cpp, util/config.cpp, util/config.h
This adds `-io-nobuiltin` commandline option that encodes standard I/O functions as unknown.
InstCombine is the only optimization that transforms standard I/O libraries like printf/scanf/... into something else, so this flag can be turned on when the optimization does not have instcombine.
=> Add an option that encodes standard I/O functions as unknown fns

ir/memory.cpp
This caused invalidexpr errors after #398 and nofree are landed because many io functions are labeled as nofree.
=> non_local_block_liveness should be preserved if nofree exists

tools/transform.cpp
I see that oggenc takes pretty long time (> 10hrs when run in parallel) in preprocessing only, and for some pairs substituting boolean qvars with true + false was the place .
I put hit_half_memory_limit() so the loop stops if the expression gets too large.
=> Check hit_half_memory_limit while substituting qvars

ir/memory.cpp
I think zero_bits_offset should be fixed because bits_byte can be larger than 8 if all loads/stores have >1 alignments whereas the pointers may have offsets that have non-multiple of align.
=> zero_bits_offset should return zero if addresses observed

smt/expr.cpp
Some binary operations in Z3 can take more than 2 arguments, and `expr::isBinOp(expr &a, expr &b, int z3op)` should either fail or rebuild subexpressions that fit in 'a op b'.
But `Z3_get_domain_size` which is used in expr::isBinOp returns 2 regardless of how many operands the expression has, making the remaining operands lost.
`Z3_get_app_num_args` can be used instead to make it fail successfully.
=> Use Z3_get_app_num_args instead

ir/function.cpp, ir/function.h, ir/globals.cpp, ir/globals.h, ir/instr.cpp, ir/memory.cpp, ir/memory.h, ir/state.cpp, ir/state.h, smt/ctx.cpp, smt/expr.cpp, tests/alive-tv/memory/memset-large.src.ll, tools/transform.cpp
Unfortunately I had to replace the single memory implementation, but I'll reimplement it later as it's good for comparison.
Results time-wise are similar, but we get fewer OOMs and more bugs found:
```
file        | OOM | domain | memory | precondition | poison | total |
---------------------------------------------------------------------
bzip2.ic0   |  2  |        |        |      11      |        |  13   |
bzip2.ic6   |  1  |        |        |      11      |        |  12   |
gzip.ic0    |  2  |        |        |      11      |        |  13   |
gzip.ic6    |  1  |        |        |      11      |        |  12   |
oggenc.ic0  |  7  |   6    |   1    |      13      |        |  27   |
oggenc.ic6  |  6  |   6    |   1    |      13      |        |  26   |
ph7.ic0     |  1  |   67   |   5    | …
```
=> Introduce multi-memory implementation

ir/memory.cpp, tests/alive-tv/attrs/nonnull-bugfix.srctgt.ll
(special thanks to dongjoo)
Non local block's address cannot be zero if it is not null blk regardless of whether it was freed or not.
=> Non local block's address cannot be zero if it is not null blk

tests/alive-tv/bugs/pr24179-unrolled.srctgt.ll
It was nontrivial to unroll other bugs.
As this was the only one which explicitly raised false negative, unroll this only
=> Add unrolled pr24179

README.md
LLVM_DIR is an internally set variable by find_package. It's better to
prioritize finding it through the standard search mechanisms, rather
than directly setting this.
=> Fix recommending abnormal cmake usage in the build directions

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/state.cpp, ir/value.cpp, tests/alive-tv/attrs/noundef-callsite.srctgt.ll, tests/alive-tv/attrs/noundef-fndef.srctgt.ll, tests/alive-tv/attrs/noundef-ret-callsite.srctgt.ll, tests/alive-tv/attrs/noundef-ret-fndef.srctgt.ll, tests/alive-tv/attrs/noundef-ret.srctgt.ll, tests/alive-tv/attrs/noundef-ret2.srctgt.ll, tests/alive-tv/attrs/noundef-ret3.srctgt.ll, tests/alive-tv/attrs/noundef-ret4.srctgt.ll, tests/alive-tv/attrs/noundef.srctgt.ll, tests/alive-tv/attrs/noundef2.srctgt.ll
Since it is an important attribute, I made a patch that adds it.
noundef for aggregate is left as unsupported, because noundef does not constraint padding of aggregate values to be non-undef.
It reuses the undef-checking function that is used by br/switch to encode UB.
=> Support noundef attribute

ir/state.cpp, tests/alive-tv/calls/issue455.srctgt.ll
The memory to synchronize should be the return memory of the source, otherwise it may miss memories from some returning blocks.
=> Fix issue 455

ir/memory.cpp, ir/memory.h
This PR is purely about suggesting renaming global vars/fn that are related with nonlocal bids + adding a comment.
- It seems `next_nonlocal_bid` is only used to calculate the bid of new global blocks, so renamed to `next_global_bid`.
- `next_nonlocal_ptr` contains bid, so `next_nonlocal_bid` is used instead. Similarly for `nextNonlocalPtr()`.
- Left a comment that describes how nonlocal bids are assigned.
Would this PR make sense?
=> Renaming nonlocal related globals/fns

ir/memory.cpp
This removes `isHeapAllocated().implies` as discussed before
LLVM unit tests: no regression
Single file benchmark: [results.txt](https://github.com/AliveToolkit/alive2/files/5078492/results.txt); the new incorrect pairs in sqlite3 are miscompilations (a known bug in simplifycfg that introduces UB)
=> Update local block refinement rule

ir/instr.cpp
freeze should keep padding poison when returning an aggregate value.
This resolves `test/Transforms/InstSimplify/freeze-noundef.ll` 's failure:
```
define {i8, i24, i32} @aggr({i8, i24, i32} noundef %x) {                           
%0:                                                                                
%y = freeze {i8, i24, i32} noundef %x                                            
ret {i8, i24, i32} %y                                                            
}                                                                                  
=>                                                                                 
define {i8, i24, i32} @aggr({i8, i24, i32} noundef %x) {                           
%0: …
```
=> Freeze should keep padding poison

ir/memory.cpp, tests/alive-tv/memory/aggregate-padding.srctgt.ll
No regression from LLVM unit tests.
I'll run single file benchmarks too & see whether there is any failure.
If there is no failure, I think I can send the suggestion to llvm-dev.
=> Automatically fill padding with poison when loading an aggregate value

ir/type.cpp, tests/alive-tv/attrs/noundefaggr-empty.srctgt.ll, tests/alive-tv/emptyaggr-load.srctgt.ll, tests/alive-tv/emptyaggr-store.srctgt.ll, tests/alive-tv/emptyaggr-store2.srctgt.ll, tests/alive-tv/emptyaggr.srctgt.ll
This patch encodes an empty aggregate as a statevalue `{expr::mkUInt(0, 1), expr::mkUInt(1, 1)}`.
I used uint for non-poison to make `AggregateType::np_bits` return a valid value.
LLVM unit tests: no failure regression, no invalidexpr test added
=> Fix invalid expr error when an empty struct is used

llvm_util/llvm2alive.cpp
This fixes the following compiler warning generated by Clang:
[42/73] Building CXX object CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o
../llvm_util/llvm2alive.cpp:1007:26: warning: loop variable 'dst' is always a copy because the range of type 'llvm::succ_range' (aka 'iterator_range<SuccIterator<llvm::Instruction, llvm::BasicBlock> >') does not return a reference [-Wrange-loop-analysis]
for (const auto &dst : llvm::successors(&bb)) {
^
1 warning generated.
=> fix clang compiler warning

ir/instr.cpp, ir/instr.h, ir/state.cpp, ir/state.h
This implements #468.
This removes one timeout from Alive2 unit tests.
I'll run & leave the LLVM unit test / single file benchmark results here.
=> Add poison analysis

tests/alive-tv/globals/const2.srctgt.ll, tools/transform.cpp
can_remove_init should consider pointer comparison because a pointer that is equal to the const global may be used to read the data.
=> can_remove_init should consider pointer comparison

ir/instr.cpp, ir/instr.h, tests/alive-tv/attrs/dereferenceable-align-fail.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite-align-fail.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite-max.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite.srctgt.ll, tests/alive-tv/attrs/dereferenceable-callsite2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-fndef3.srctgt.ll, tests/alive-tv/attrs/dereferenceable-nofree.srctgt.ll, tests/alive-tv/attrs/dereferenceable-ret-callsite-align.srctgt.ll, tests/alive-tv/attrs/dereferenceable-ret-callsite.srctgt.ll, tests/alive-tv/attrs/dereferenceable-ret-callsite2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-shrink.srctgt.ll, tests/alive-tv/attrs/dereferenceable.srctgt.ll, tools/transform.cpp
IMO this happened because FnCall wasn't defined as a subclass of MemInstr.
I changed FnCall to inherit MemInstr.
=> Fix a bug of dereferenceable attribute (it should not guarantee the pointer is aligned)

ir/attrs.h, ir/instr.cpp, ir/state.cpp, ir/value.cpp
This is a refactoring that adds undefImpliesUB, poisonImpliesUB which return whether passing undef/poison to an argument with the attributes or returning undef/poison at the end of a function call is UB.
=> Add undefImpliesUB, poisonImpliesUB

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/state.cpp, ir/state.h, ir/value.cpp, ir/value.h, tests/alive-tv/undef/opt-noundef.srctgt.ll
This is a patch that follows #472 .
This patch adds a boolean argument to `State::getAndAddPoisonUB` that states whether passing an undef is UB as well and should strip it.
Consists of two commits - with the first commit only, the result of single file benchmark didn't improve. 
With the second comment, on my machine, `alive-tv/memory/storeptr.src.ll` raises no more timeout (became 2.7 sec). Single file benchmarks and unit tests are running.
But the second commit requires an assumption that passing a partially undefined pointer to load/store raises UB. I think this can be justified because memory sanitizer also detects such case (when an 'expensive detection' flag is turned on)
=> Add undef analysis

smt/ctx.cpp, smt/smt.cpp, smt/smt.h, tools/alive-tv.cpp, tools/alive.cpp, tv/tv.cpp
This PR adds a `-smt-random-seed` parameter that sets the value of `smt.random_seed` of Z3.
=> Add -smt-random-seed

llvm_util/llvm2alive.cpp
Since https://reviews.llvm.org/D88787 / https://github.com/llvm/llvm-project/commit/322d0afd875df66b36e4810a2b95c20a8f22ab9b they are no longer experimental.
=> [LLVM] Vector reductions are no longer experimental

ir/attrs.cpp, ir/attrs.h, ir/function.cpp, ir/function.h, tests/alive-tv/issue476.srctgt.ll, tools/alive-tv.cpp, tools/transform.cpp
This patch resolves #476 by conservatively checking whether src/tgt have same param attributes.
=> Check whether src and tgt have same param attributes

ir/instr.cpp, tests/alive-tv/switch.srctgt.ll, tools/alive-exec.cpp
This patch contains a few minor patches:
- free's ptr argument is noundef
- a simple switch test (there hasn't been switch test)
- remove unused variable from alive-exec.cpp
=> Free's ptr arg is noundef, minor patches

ir/function.h, tv/tv.cpp
This patch makes clang plugin skip functions if they have no diff in Alive2 IR.
=> Skip functions that have no diff (clang plugin)

tv/tv.cpp
... and the printing message does not reflect that.
This is a simple patch that updates it
=> If opt_error_fatal is false, tv doesn't abort

tv/tv.cpp
A super simple patch that adds `InferFunctionAttrsPass` to the list of optimizations to skip.
=> Add InferFunctionAttrsPass to the skip list

ir/state.cpp, ir/state.h, tools/transform.cpp
This patch adds `unused_vars` to value analysis, to support the optimization discussed yesterday
=> Don't undef rewrite if unused in the ctrl flow

llvm_util/known_fns.cpp
They appeared at `Unsupported known functions` list after running clang tv on SPEC CPU benchmarks
=> Add a few more I/O functions to ignore

tv/tv.cpp
... due to two reasons.
(1) Non-zero exit makes `make` stop
(2) It prevents clang from doing cleanup, leaving temporary files in the current directory (name of which is something like `<filename>-cfad9157.ll.tmp`)
=> don't exit if clang plugin is used

tv/tv.cpp
This is helpful for reducing the size of logs.
The same parameter exists in alive-tv.
=> Add -tv-succinct

ir/attrs.cpp, ir/attrs.h, ir/function.h, ir/instr.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/returned-2.srctgt.ll, tests/alive-tv/attrs/returned-3.srctgt.ll
This patch adds support for `returned` attribute.
My machine for LLVM unit test is preoccupied with the updated fabs patch, I will leave report here after testing fabs and this patch is done
=> Add returned attribute

CMakeLists.txt, README.md, scripts/alivecc.in, scripts/opt-alive.sh.in
also, fixup paths in our opt replacement
=> add simple compiler drivers alivecc and alive++ that load our clang plugin transparently

tv/tv.cpp
This is a feature I'd like because I'm comparing report directories to sanity-check my redis caching code, and the random filenames are making this more difficult than it needs to be.
=> optionally, don't avoid overwriting existing report files using random file names

tv/tv.cpp
It's already done for all other options, just not these.
=> TV: group all options into a grop, to make --help more readable

ir/function.cpp
In getDepthFirstSpanningTree(), using map "number" to avoid revisiting is buggy. The map "number" updates only after a node is visited. Before a node is visited, multiple pointers to that node may already be pushed to the worklist. 
Rather, we should record the basicblock immediately after the basicblock being pushed.
=> Fixed a bug in loop analyzer

ir/memory.cpp, tests/alive-tv/memory/memset-align.srctgt.ll
... which caused the alignment of null block between src and tgt to be arbitrarily different, causing false positive.
=> null block's alignment encoding was missing

ir/state.cpp, tests/alive-tv/calls/readnone-duplicated.srctgt.ll
This is my solution of https://github.com/AliveToolkit/alive2/issues/477#issuecomment-719904013 .
IIUC, `analysis.ranges_fn_calls` states how many other functions have been called before the current function call is reached.
This is used to prune out pairwise equivalence encoding between function calls by ignoring calls from different input memory state.
However, if a function never reads memory, outputs are equivalent regardless of the input memory.
`analysis.ranges_fn_calls` should not prune out the equivalence encoding of such no-read calls in this case.
=> make fn call range empty if function never reads memory

ir/function.cpp
entry node is self pointing so when the dominates() hit entry bb, it'll stuck in the while infinitely.
=> bug fix: break on self pointing dom node so that .dominates() terminates

ir/function.cpp, tests/alive-tv/loops/issue558.srctgt.ll
- Recompute dom tree after each unroll
- Jump over empty bb (#sink) in CFG::edge_iterator::next()
=> Recompute dom tree after each unroll

ir/memory.cpp, tools/transform.cpp
This PR resolves Transforms/GVN/pr25440.ll.
`Function::unroll()` can create an alloca whose size is `Memory::getStoreByteSize`, but pointer's store size is returning zero because `bits_program_pointer` isn't initialized yet.
=> bits_program_pointer should be initialized in advance

ir/function.cpp, tests/alive-tv/loops/issue562.srctgt.ll
Not all of the sources of phi is using the value we're replacing. We only patch the designated phi source. This patch fixes issue https://github.com/AliveToolkit/alive2/issues/562.
=> loop: do not replace the source which has value different than val

tools/transform.cpp
`unit/call-error*.opt` has fn calls, which causes `Memory::alloc` to be called due to the existence of a null block. But, `Memory::alloc` crashes when `bits_program_pointer` is zero because it calls `expr::mkUInt` with zero bit size.
=> fix buildbot crash

tests/alive-tv/bugs/pr1014-nolocal.srctgt.ll, tests/alive-tv/bugs/pr1014.srctgt.ll, tests/alive-tv/bugs/pr1111.srctgt.ll, tests/alive-tv/bugs/pr1244.srctgt.ll, tests/alive-tv/bugs/pr22727.srctgt.ll, tests/alive-tv/bugs/pr27036.srctgt.ll, tests/alive-tv/bugs/pr31633.srctgt.ll, tests/alive-tv/bugs/pr34349.srctgt.ll, tests/alive-tv/bugs/pr38461.srctgt.ll, tests/alive-tv/bugs/pr39861.srctgt.ll, tests/alive-tv/bugs/pr42198.srctgt.ll, tests/alive-tv/bugs/pr42619.srctgt.ll, tests/alive-tv/bugs/pr43665.srctgt.ll, tests/alive-tv/bugs/pr43689.srctgt.ll, tests/alive-tv/bugs/pr43730.srctgt.ll, tests/alive-tv/bugs/pr43802.srctgt.ll, tests/alive-tv/bugs/pr44186.srctgt.ll, tests/alive-tv/bugs/pr44383.srctgt.ll, tests/alive-tv/bugs/pr6940.srctgt.ll
This PR contains 18 more src/tgt pairs harvested from bugzilla.
Finding a bug from `pr1014.srctgt.ll` required precise encoding of escaped local blocks, so I wrote `pr1014-nolocal.srctgt.ll` and checked that a bug was found.
`pr22727.srctgt.ll` shows that it was actually not a bug.
=> add more bug reproducers

tv/tv.cpp
This patch passes an empty set to `gvnamesInSrc` when recreating tgt.
`gvnamesInSrc` specifies which global variables should exist in tgt.
The recreated tgt works as src in the next pass, so the information is not necessary.
In reality, this issue was slightly more complex: before https://github.com/AliveToolkit/alive2/commit/4d914925428cc4be6b5eb33427e611e44800b71a was added, src's global vars were being passed to descendants all the way.
But, `removeUnused()` (which was called by `preprocess()`) was removing unused global variables, so things were okay.
To summarize, before https://github.com/AliveToolkit/alive2/commit/4d914925428cc4be6b5eb33427e611e44800b71a, tv was depending on `preprocess()` to keep tgt in a good state. :/
I believe making the new tgt independent from preprocess() is …
=> tv: when recreating tgt, pass an empty set to gvnamesInSrc

CMakeLists.txt, tv/CMakeLists.txt
=> only install clang drivers if we're building the clang plugin

scripts/alivecc.in, tests/clang-tv/interprocedural.cpp, tests/clang-tv/issue569.cpp, tests/clang-tv/issue579.c, tests/lit/lit/formats/alive2test.py
This PR adds lit test for clang tv (#585 ).
It invokes `scripts/alivecc` or `scripts/alive++` if the file exists (otherwise it marks the test as unsupported).
Another minor edit in this PR is that `scripts/alivecc.in` is updated to use `.dylib` extension when used in Mac.
=> clang tv: add lit test

tests/alive-tv/attrs/dereferenceable-align-fail2.srctgt.ll, tests/alive-tv/attrs/dereferenceable-align.srctgt.ll, tools/transform.cpp
This fixes another bug regarding `dereferenceable`.
The bug is similar to the one in #442 , but this PR's fix has a smaller code change.
=> take arguments' align into account when calculating bits_byte

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/memory.cpp, ir/value.cpp, llvm_util/llvm2alive.cpp, tools/transform.cpp
The recent two crashes are due to the inconsistent use of attr's align field.
The field is storing log(alignment), but ir/value.cpp was assuming the value was simply storing the alignment.
This PR changes attr's align field to store the original value
=> change attr's align field to store the original value

ir/instr.cpp, tests/alive-tv/opt-memory/deref-align-callee.srctgt.ll, tests/alive-tv/opt-memory/deref-align-callee2.srctgt.ll
=> consider fncall param aligns when calculating access size

CMakeLists.txt
there's no built-in cmake functionality for this, but the new macro appears to do the job properly.
=> strip out the automatically-added -DNDEBUG compiler flag, so that we get assertions in Release builds

tv/tv.cpp
The TargetLibraryInfoImpl temporary object passed to the constructor of TargetLibraryInfo is destroyed after the constructor is finished.
This causes use-after-free at llvm2alive calls afterward.
Adding John's reduced code as a unit test requires passing
```
-isysroot `xcrun --show-sdk-path`
```
to clang on Mac because the test is including a header file.
I'll add this test after the alivecc script is updated.
=> clang tv: fix a use-after-free bug

CMakeLists.txt, scripts/opt-alive.sh.in, tests/lit/lit/formats/alive2test.py, tests/opt-tv/printf.opt.ll, tests/opt-tv/test.opt.ll
This PR resolves #95 : adds support for running lit testing with the opt Alive2 plugin.
=> add unit test support for opt plugin

CMakeLists.txt, README.md, scripts/fix_report_files.in, tv/CMakeLists.txt, tv/tv.cpp, util/parallel.h, util/parallel_jobserver.cpp, util/parallel_unrestricted.cpp
parallelism managers: one that just forks in uncontrolled fashion (for
testing and debugging -- don't run it on large inputs) and another
that uses the jobserver from GNU make to limit parallelism.
when output in not directed to a report directory, it all just gets
blatted to the terminal in mixed-up fashion by all the different
proceses. when output is directed to a report directory, it goes to a
lot of little individual files and then a utility fix_report_files
stitches it all back together.
=> run TV from our LLVM plugin in parallel by forking. provide two

ir/function.cpp, tests/alive-tv/loops/issue582.srctgt.ll
When dealing with multi-entering phi without loop carried dependencies, if the copies is empty after copies.pop_back(), we need also erase the key (val) from the vmap. If we don't erase, vmap would contain keys with empty values. L403 would be reachable for such keys. Since calling back() on an empty vector is UB, dereferencing the result leads to the crash listed in issue #582.
https://github.com/AliveToolkit/alive2/blob/e58c28cc61798140151d1fcd4064616740c71559/ir/function.cpp#L403
=> fix issue #582: crash in basicblock duplication

llvm_util/llvm2alive.cpp, llvm_util/utils.cpp, llvm_util/utils.h
I'm sorry for the delay, I had a few things that had to be done today.
This is a super small patch that adds getter/setter for `out` that can be used to change ostream that is used by llvm2alive.cpp .
I think `initializer` does not require ostream argument anymore, but it is left unchanged because it needs updates in tv.
=> add get_outs/set_outs

scripts/benchmark_clang_tv.in, tv/CMakeLists.txt
hopefully be using for the "real world benchmarks" part of the next
revision of the alive2 paper.
note that I while I used the same programs that Juneyoung had
previously been using, I did not attempt to use the same versions of
these programs
for example, the latest version of oggenc is not available standalone,
so I rather selected libogg as the benchmark as it contains core code
and takes about the right amount of time
=> ok, this is the initial version of a script that contains what we'll

README.md, scripts/opt-alive.sh.in, scripts/rewritepass.py, tests/opt-tv/npm-Os.opt.ll, tests/opt-tv/npm-globalopt.opt.ll, tests/opt-tv/npm-lu.opt.ll, tests/opt-tv/npm-lu2.opt.ll, tests/opt-tv/npm-verify.opt.ll, tests/opt-tv/npm.opt.ll, tests/opt-tv/npm2.opt.ll, tests/opt-tv/npm3.opt.ll, tv/CMakeLists.txt, tv/tv.cpp
This PR resolves #330 .
LLVM unit test results (I ran tests that contain `-passes=` only)
New failures:
```
Transforms/InstCombine/infinite-loop-postdom.ll (tv interacts with ‘print’ pass)
Transforms/LoopRotate/pr35210.ll (it checks the list of optimization passes)
Transforms/MergeICmps/X86/pair-int32-int32.ll (related to memcmp’s semantics)
Transforms/SimpleLoopUnswitch/nontrivial-unswitch.ll (loop switch)
Transforms/SimpleLoopUnswitch/trivial-unswitch.ll (and -> conditional branch)
```
Unknown assertion failure:
```
Transforms/Attributor/align.ll 
```
(failures from the tests that use legacy pass managers are excluded)
=> add support for opt new pass manager unit tests

scripts/alivecc.in
I promise to maintain this code for the foreseeable future
this adds some functionality
that would be pretty cumbersome in bash. first, try to detect being
invoked as something other than a compiler (linker, assembler, ...)
and then don't load the alive2 plugin, which would cause problems
because it then fails to intercept our command line arguments, causing
some build systems to error out.
second, we now communicate our wishes to alivecc using environment
variables. this simplifies build system interactions since we no
longer have to try to override CFLAGS, which doesn't uniformly work
across packages. additionally, overriding CFLAGS is fragile when clang
gets invoked as a linker/assembler, again causing problems.
I didn't add a very large set of flags, only the ones I'm using commonly …
=> this is a rewrite of alivecc in perl

llvm_util/llvm2alive.cpp, tests/alive-tv/trap-and-plainfn-distinct-rev.srctgt.ll, tests/alive-tv/trap-and-plainfn-distinct.srctgt.ll, tests/alive-tv/trap-and-plainfn-distinct2-rev.srctgt.ll, tests/alive-tv/trap-and-plainfn-distinct2.srctgt.ll, tests/alive-tv/trap-and-plainfn-distinct3-rev.srctgt.ll, tests/alive-tv/trap-and-plainfn-distinct3.srctgt.ll, tests/alive-tv/trap.srctgt.ll, tests/alive-tv/trap2.srctgt.ll, tests/alive-tv/trap3.srctgt.ll, tests/alive-tv/trap4.srctgt.ll
This PR uses a function call to encode llvm.trap.
The benefit of encoding it as a function call is that it is easy to check refinement of llvm.trap and other no-return function calls.
I found that it becomes a bit non-trivial for me to do without function call encoding (for example, simply making it do `state.addNoReturn()` will allow the refinement).
We already have a nice framework that works really well for encoding the equivalence of function calls using UB.
A limitation of this encoding is that we can't impose `call llvm.trap()` to never have UB.
It can introduce false positive in theory (because llvm.trap has more behavior than people's thought), but.. I couldn't come up with an example that has false positive.
=> support llvm.trap

scripts/benchmark-clang-tv.in, scripts/benchmark-llvm-test-suite.in, tv/CMakeLists.txt
add embench and musl -- they're interesting codes that take about the right amount of time
comment out ph7 and sqlite3 until we make things faster/more parallel
switch over to communicating with alivecc using environment variables
instead of command line options
add a second benchmarking script that tries to do TV for the
SingleSource part of the LLVM test-suite. this doesn't work yet and
will require a lot of CPU time once it does work (this dir is like
300,000 lines of code) but I think it's the rigth direction for us.
=> more work in benchmarking scripts

scripts/benchmark-llvm-test-suite.in
only compile C code with alive2, for C++ just use clang++
this configuration takes about 15 minutes on my group's big 128-thread machine
=> run only the MicroBenchmarks and SingleSource dirs

tv/tv.cpp, util/parallel.cpp, util/parallel.h, util/parallel_jobserver.cpp, util/parallel_unrestricted.cpp
buffered output from all children and then dumped it all at once at
the end. this hurt when using alivecc on huge files like sqlite3.c.
this patch dumps output as it goes along. the only tricky thing was
dealing with the fact that children complete out of order.
this also does just a tiny bit of cleanup on the parallel manager.
tested by running alivecc in serial and parallel modes and making sure they print mostly the same thing
=> Print output earlier

llvm_util/known_fns.cpp, tests/alive-tv/libcalls/access.srctgt.ll, tests/alive-tv/libcalls/gettimeofday.srctgt.ll
access: frequently used by sqlite3 (2nd)
```
declare noundef i32 @access(i8* nocapture noundef readonly, i32 noundef) nofree nounwind
```
gettimeofday: frequently used by SingleSource+Microbenchmarks (5th)
```
declare noundef i32 @gettimeofday(%opaque* nocapture noundef, i8* nocapture noundef) nofree nounwind
```
LLVM does not have optimizations that use these.
=> support gettimeofday, access

CMakeLists.txt, README.md, scripts/alivecc.in, tools/alive-jobserver.cpp, tv/tv.cpp, util/parallel.cpp, util/parallel.h, util/parallel_fifo.cpp, util/parallel_null.cpp, util/parallel_posix.cpp
first, a trivial one that doesn't actually call fork, it just drops
all TV work onto the floor. the intent is to make it easy to examine
our sequential critical path by ignoring everything else.
second, a new jobserver based on a named pipe. this ends up being
quite a lot easier and simpler than interacting with the GNU make
jobserver which has some gotchas.
=> two new parallel managers

ir/instr.cpp, tests/alive-tv/shufflevec-undef.srctgt.ll
Transforms/Scalarizer/order-bug.ll is failing because shufflevector isn't rewriting undef per element
A reduced example:
```
define <2 x i32> @src(i32 %a) {
%ie = insertelement <2 x i32> poison, i32 %a, i32 0
%ret = shufflevector <2 x i32> %ie, <2 x i32> poison, <2 x i32> <i32 0, i32 0>
; It should be allowed that %ret[0] and %ret[1] may have undef value independently
ret <2 x i32> %ret
}
define <2 x i32> @tgt(i32 %a) {
%ie = insertelement <2 x i32> poison, i32 %a, i32 0
%ret = insertelement <2 x i32> %ie, i32 %a, i32 1
ret <2 x i32> %ret
}
```
Note that the ongoing shufflevector semantics patch is orthogonal to this fix because all masks are non-undef.
=> shufflevector should rewrite undef per element

tests/alive-tv/loops/scev-exactnottaken.srctgt.ll, tests/alive-tv/loops/scev-exactnottaken2.srctgt.ll, tests/alive-tv/loops/scev-exactnottaken3.srctgt.ll, tests/alive-tv/loops/scev-exactnottaken4.srctgt.ll, tests/alive-tv/loops/scev-exactnottaken5.srctgt.ll, tests/alive-tv/loops/scev-exactnottaken6.srctgt.ll, tests/alive-tv/loops/scev-exactnottaken7.srctgt.ll
This patch adds tests from https://reviews.llvm.org/D93882 's Alive2 links.
The tests have src/tgt functions where tgt has `llvm.assume` calls introduced to show that the exit value of `i` should/shouldn't be min/max of n, m.
=> Add tests from D93882

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/value.cpp, tests/alive-tv/attrs/byval-dereferenceable.srctgt.ll, tests/alive-tv/attrs/byval-dereferenceable2.srctgt.ll
This patch adds dereferenceable check if a pointer argument has byval attribute.
=> add dereferenceable constraint when encoding byval attr

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/value.cpp, tests/alive-tv/attrs/align-callsite-withnoundef.srctgt.ll, tests/alive-tv/attrs/align-callsite.srctgt.ll, tests/alive-tv/attrs/align-callsite2-withnoundef.srctgt.ll, tests/alive-tv/attrs/align-callsite2.srctgt.ll, tests/alive-tv/attrs/align-callsite3-withnoundef.srctgt.ll, tests/alive-tv/attrs/align-callsite3.srctgt.ll, tests/alive-tv/attrs/align-callsite4.srctgt.ll, tests/alive-tv/attrs/align-fndef2.srctgt.ll, tests/alive-tv/attrs/align-fndef3.srctgt.ll, tests/alive-tv/attrs/align-fndef4.srctgt.ll, tests/alive-tv/attrs/align-intro-withnoundef.srctgt.ll, tests/alive-tv/attrs/align-intro.srctgt.ll, tests/alive-tv/attrs/align-ret-callsite3.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite-withnoundef.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite2-withnoundef.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite4-withnoundef.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite5-withnoundef.srctgt.ll, tests/alive-tv/attrs/nonnull-callsite6.srctgt.ll, tests/alive-tv/attrs/nonnull-fndef2.srctgt.ll, tests/alive-tv/attrs/nonnull-fndef3.srctgt.ll, tests/alive-tv/attrs/nonnull-fndef4.srctgt.ll, tests/alive-tv/attrs/nonnull-gep.srctgt.ll, tests/alive-tv/attrs/nonnull-intro-withnoundef.srctgt.ll, tests/alive-tv/attrs/nonnull-ret-callsite2.srctgt.ll
Since the nonnull patch (https://reviews.llvm.org/D90529) is likely to be landed soon..! (this Tuesday, unless there is a new request)
This is a patch that makes nonnull/align use the poison semantics rather than immediate UB.
LLVM unit tests running...
Relevant issue: #493
=> make nonnull/align pass poison rather than raise UB

tests/alive-tv/params/dbg.src.ll, tests/lit/lit/formats/alive2test.py, tools/alive-tv.cpp
As clang-tv does, this patch makes alive-tv omit pairs having equivalent Alive2 IRs.
If `-always-verify` is given, alive-tv verifies it even if they are equivalent. This is used by Alive2 unit tests.
=> Add syntactic equality check to alive-tv

ir/function.cpp
Compiling Alive2 with Debug mode & running `ninja check` shows a few failures due to container-overflow bugs.
(https://llvm.org/devmtg/2014-04/PDFs/LightningTalks/EuroLLVM%202014%20--%20container%20overflow.pdf )
There were two buggy places, both of which are:
```
auto &v = vector.back()
vector.pop_back()
use(v)
```
For LoopAnalysis::getDepthFirstSpanningTree, I moved the pop_back to the end of the if branch.
For Function::unroll, the function was quite complex, so I just tagged off `&`.
=> fix container-overflow bugs detected by asan

ir/memory.cpp, tests/alive-tv/memory/issue651-2.srctgt.ll, tests/alive-tv/memory/issue651.srctgt.ll
When load returns a pointer, the pointer's bid is to be POR-ed.
However, if the returned pointer was poison, its bid has a bogus value. The POR condition should take this into account.
=> Load ptr's partial order reduction should consider non_poison into account

CMakeLists.txt
When used as a standalone project, both CMAKE_BINARY_DIR and
PROJECT_BINARY_DIR yield the same value.
However, when Alive2 added as a sub-project (via add_subdirectory),
then CMAKE_BINARY_DIR and PROJECT_BINARY_DIR are different, which leads
to a build failure.
This patch fixes the discrepancy between two different values.
P.S. Alternative solution would be to add `${CMAKE_BINARY_DIR}` to the
`include_directories`, but I think the suggested solution is better since it
doesn't "pollute" the build directory of the parent project.
=> Fix CMake binary dir discrepancy

smt/expr.h, smt/solver.h
This helps certain STL operations like `vector<expr>::push_back` to efficiently move elements to a newly allocated memory (rather than copy) when the container needs to be resized.
Without noexcept, push_back needs to copy its elements to give a strong exception guarantee (meaning that push_back should rollback to the previous state if it failed).
Move constructors at exprs.h wasn't updated because their element types are not guaranteed to have noexcept move constructors (yet).
Ref: https://stackoverflow.com/questions/20517259/why-vector-access-operators-are-not-specified-as-noexcept/20521414#20521414
=> add noexcept to move constructors

tests/alive-tv/ptr-arithmetic-fail.srctgt.ll, tools/alive-tv.cpp, tools/transform.cpp, tv/tv.cpp, util/config.cpp, util/config.h
This patch adds a max_gep_offset config option, to limit the maximum
value assumed for GEP offsets. This effectively provides an option to
limit the width of pointer arithmetic, which in turn speeds up
verification of programs using a lot of pointer arithmetic.
For regular arithmetic, a common advice is to limit the width of integer
types, but there is no easy way to  do the same thing for pointers. The
new option allows limiting the width of pointer arithmetic globally.
This should not impact soundness & completeness, unless the input
program has pointer arithmetic that does not fit in the specified width
(e.g. has a GEP that uses an offset outside the max range). So the users
of the option should think carefully when using the option.
Perhaps there is also a way to verify that the …
=> add option to limit number of bits used for GEP offsets

README.md, scripts/alivecc.in, scripts/opt-alive.sh.in, tests/opt-tv/legacypm.opt.ll, tests/opt-tv/npm-Os.opt.ll, tests/opt-tv/simple.opt.ll, tv/tv.cpp
This is a patch to resolve the failures on my machine after NPM switch is enabled (https://github.com/AliveToolkit/alive2/issues/666#issuecomment-778779487).
After the NPM switch, all pass names in opt's command line arguments are parsed and passed into NPM (unless `-enable-new-pm=0` is given). For example, running `opt -tv -instcombine -tv` lookups `tv` and `instcombine` new passes.
This again causes a nasty problem that happened before (https://github.com/AliveToolkit/alive2/commit/c6d4b33daa177d64ab4b5947253dedd7dd61ac65 ). 
opt calls alive2's `registerPipelineParsingCallback("tv")` with dummy extra arguments to investigate whether `-tv` is a module-level pass or not.
This is problematic because our `registerPipelineParsingCallback("tv")` is not *idempotent*.
It adds `TVInitPass` in …
=> Resolve unit test failures after LLVM's switch to NPM

llvm_util/known_fns.cpp
This patch resolves #675 by simply encoding free() nofree as unreachable.
=> Translate free() nofree as unreachable

scripts/opt-alive.sh.in
This resolves two regressions: Transforms/TailCallElim/opt-remarks-recursion.ll and Transforms/LoopUnrollAndJam/unroll-and-jam.ll .
opt-remarks-recursion.ll: tailcallelim is a function-level pass but unsupported by Alive2. I added a check for this.
unroll-and-jam.ll: it has tbaa enabled but still `module(tv)` was being added to -passes. We should check whether NPM is already set to 0 when adding `module(tv)`.
=> tv shouldn't run if NPM is disabled or has tailcallelim

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/value.cpp, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/dereferenceable_or_null-callsite.srctgt.ll, tests/alive-tv/attrs/dereferenceable_or_null.srctgt.ll, tests/alive-tv/attrs/dereferenceable_or_null2.srctgt.ll, tests/alive-tv/attrs/dereferenceable_or_null3.srctgt.ll, tests/alive-tv/attrs/dereferenceable_or_null4.srctgt.ll, tests/alive-tv/attrs/dereferenceable_or_null5.srctgt.ll, tests/alive-tv/attrs/dereferenceable_or_null6.srctgt.ll, tools/transform.cpp
Resolves a regression in Transforms/SimplifyCFG/UnreachableEliminate.ll
I'll leave the LLVM unit test result here when it's done
=> Add support for dereferenceable_or_null

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/type.h, ir/value.cpp
This patch goes one step further and refactors code duplication in FnAttrs <-> ParamAttrs.
=> refactor code duplication in fn/paramattr encoding

ir/memory.cpp
This breaks the symmetry of fncall's extra block and other nonlocals (the detail is sent as a mail separately)
=> factor out bid-based nonlocal block analysis

llvm_util/llvm2alive.cpp, tests/alive-tv/assume/align-op3.srctgt.ll
This patch resolves the two failures (Transforms/AlignmentFromAssumptions/simple.ll, simple32.ll) by unsupporting align with 3 arguments.
According to `llvm/lib/Transforms/Scalar/AlignmentFromAssumptions.cpp`, the extra argument seems to represent an information describing that there exists i and j s.t. `(int)ptr = ai + bj` given an operand bundle `"align"[i8* ptr, i64 a, i64 b]`, but I'm not sure.
Maybe I can ask this to people.
=> unsupport align op bundle with an extra argument

llvm_util/llvm2alive.cpp, tests/alive-tv/lifetime/lifetime-malloc.srctgt.ll, tests/alive-tv/lifetime/lifetime-malloc2.srctgt.ll, tests/alive-tv/lifetime/lifetime-undef.srctgt.ll
This patch resolves unsupported lifetime errors from:
```
InstCombine/deadcode.ll
InstCombine/malloc-free-delete.ll
MemCpyOpt/memset-memcpy-oversized.ll
DeadStoreElimination/MSSA/multiblock-multipath.ll
NewGVN/verify-memoryphi.ll
```
LoopVectorize/lifetime.ll still has unsupported lifetimes, but they look weird: https://godbolt.org/z/vf39f3
The input function already isn't looking good; lifetime.start/end is spread over entry and exit block.
The output function either has double lifetime.start or the pointer operand has `extract(...)` form.
I think this is a suboptimal form, and to help stackcoloring it should be fixed from LLVM side.
=> support lifetime undef or heap alloc

ir/memory.cpp, ir/memory.h
This is a follow-up of #654 and treats the memory block for recording fncall's side effect as global, always live, and inaccessible one. This reduces the size of may-alias sets.
Also, this updates the disjointness of blocks to never consider the fncall mem block because its address is unobservable.
Note that things can be further improved by reordering the block ids; currently, `bid != expr::mkUInt(get_fncallmem_bid(), bid);` is individually added to the may-alias SMT formula. This can be improved by reassigning fncallmem_bid to be placed after the pointers from loads/fncalls/etc.
=> Define fncall mem block as global, always-live, inaccessible one

ir/memory.cpp, ir/memory.h, tests/alive-tv/por/issue697.srctgt.ll, tests/alive-tv/por/issue697_2.srctgt.ll, tests/alive-tv/por/issue697_3.srctgt.ll
=> Initial nonlocal val cannot contain ptr to fncall mem blk

ir/memory.cpp, ir/pointer.cpp, tests/alive-tv/memory/issue689_lifetime.srctgt.ll
This patch fixes https://github.com/AliveToolkit/alive2/issues/689#issuecomment-817185265. It happened because `Pointer::mkLongBid`'s second argument (local flag) was incorrectly set to false.
I added an assertion there to sanity-check whether `local` isn't bogus.
=> disjoint_local_blocks should use local pointers to compare addrs

scripts/alivecc.in, scripts/benchmark-llvm-test-suite.in, tests/clang-tv/quiet.c
This patch fixes alivecc to use -tv-quiet instead & add a test that checks whether the option works.
=> Fix alivecc to pass -tv-quiet, add a test for the option

tv/tv.cpp
To simplify implementing the batch option, this patch factors out verify part from `TVLegacyPass::runFunction`.
The new `verify` static function takes `Transform` object as well as `FnInfo` and has all the important part.
`TVLegacyPass::runFunction` mainly calls `llvm2alive` to fill the objects.
With this patch, batched opt becomes simpler because what it needs to do is to pre-build src/tgt pair and simply call this `verify` whenever an unsupported optimization is met.
=> split TVLegacyPass::runFunction into preparation & verify

tests/alive-tv/ptrcmp/D99642.srctgt.ll
`; CHECK: %c = icmp eq i8* %q, null` in the original source confused alive2test, sorry. :/
=> Fix D99642

ir/instr.cpp, ir/instr.h, tests/alive-tv/opt-memory/ptrcmp-null.ident.ll, tests/alive-tv/opt-memory/ptrcmp-null2.ident.ll, tests/alive-tv/opt-memory/ptrcmp-sameorigin.ident.ll, tests/alive-tv/opt-memory/ptrcmp-sameorigin2.ident.ll, tests/lit/lit/formats/alive2test.py, tools/transform.cpp
This is a patch that optimizes pointer comparison encoding by comparing provenance only if one of these two conditions is met:
- p == null where p is inbounds
- p == q where p and q share the same origin
=> only use provenance when comparing equality with null or same origin

ir/memory.cpp, tests/clang-tv/parallel-alias-stats.c, tv/tv.cpp
Currently clang plugin's `-mllvm -tv-alias-stats` isn't working because the statistics accumulated in the child process isn't being summed up to the parent process.
This is a small patch that makes children to print the statistics.
=> clang plugin: let stats cmd flag work by printing it when child exits

util/parallel.cpp
This fixes #720 by fixing `parallel::emitOutput()` to clip out the lines before the line read by `getline`.
An example: https://gist.github.com/aqjune/2ea18cefa4fc1fd98ba1e47ddeab5f97
I never knew that `sstream::str` has the full string even if it is being consumed :(
=> clang plugin: the messages before getline should be clipped out

tools/transform.cpp
```
[ 50% 28/55][ 30% 0:00:02 + 0:00:05] Building CXX object CMakeFiles/tools.dir/tools/transform.cpp.o
FAILED: CMakeFiles/tools.dir/tools/transform.cpp.o
/usr/local/bin/clang++  -I../ -I. -I/repositories/llvm-project/llvm/include -I/builddirs/llvm-project/build-Clang12/include -Wall -Werror -march=native -fPIC  -O3 -O3    -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++20 -MD -MT CMakeFiles/tools.dir/tools/transform.cpp.o -MF CMakeFiles/tools.dir/tools/transform.cpp.o.d -o CMakeFiles/tools.dir/tools/transform.cpp.o -c ../tools/transform.cpp
../tools/transform.cpp:780:8: error: variable 'has_vector_bitcast' set but not used [-Werror,-Wunused-but-set-variable]
bool has_vector_bitcast = false;
^
1 error generated.
[ 76% 42/55][ 94% …
```
=> Fix build with fresh clang

ir/instr.cpp, smt/expr.cpp, tests/alive-tv/fp/fptosi-nonpoison.srctgt.ll, tests/alive-tv/fp/fptoui-nonpoison.srctgt.ll, tests/alive-tv/fp/fptoui-rtz.srctgt.ll
As mentioned in https://reviews.llvm.org/D106053#2885236 , the encoding of fptoui/si is buggy.
`fptoui float 31.5 to i32' was yielding poison because np was `(float)(i32)31.5 == 31.5' which is alway false.
The rhs is fixed to round towards zero so that it becomes `(float)(i32)31.5 == round_towards_zero(31.5)'.
Also, fptoui should round towards zero according to LangRef, but it was using nearest ties to even.
This is fixed as well.
=> Two bug fixes in fpto*i

ir/instr.cpp
Adds `extract_value` as a side effect-less instruction.
As a caution:
I noticed that pre-processing and the dead code elimination step runs before the typechecking/index checking of `extractvalue` when passing the IR straight into the verifier (bypassing the parser).
(See: https://github.com/AliveToolkit/alive2/blob/e7805d6f5eadd0e10b49f8a4470f7754777dbdbb/tv/tv.cpp#L256)
This means that if we have some code along the lines of:
```
%1006_0 = sadd_overflow {i32, i1, i24} noundef %187, noundef %188
%1006_1 = extractvalue {i32, i1, i24} %1006_0, 13
```
and `%1006_1` is unused, then we will optimize it out and no typecheck error will be thrown.
I'm not sure if we want to preserve these typechecking errors, or even throw them earlier so they get caught before preprocessing, but that will need …
=> Add extract_value as a side effect-less instruction

tests/alive-tv/ptrcmp/slt.srctgt.ll, tools/transform.cpp
This fixes a bug due to an incorrect ptr comparison encoding.
Consider `p = gep inbounds p0, 0`, `q = gep inbounds p0, 1` where p0 points to the beginning of some block.
`icmp slt p, q` cannot be optimized to a comparison of their block offsets `icmp slt 0, 1` because the block p0's address may be 0x7fffffff (which is signed_int_max).
In this case, q=p+1 is 0x80000001, which is signed_int_min.
Therefore, `icmp slt p, q` is false, whereas `icmp slt 0, 1` is true.
The counter example of `slt.srctgt.ll` shows the case:
```
ERROR: Value mismatch                                
Example:                                             
* %ptr = pointer(non-local, block_id=1, offset=5)    
Source: 
* %first1 = pointer(non-local, block_id=1, offset=5)
* %last1 = pointer(non-local, block_id=1, …
```
=> Signed comparison of pointers must compare underlying addrs

ir/instr.cpp, tests/alive-tv/fp/D113543-fptosi.srctgt.ll, tests/alive-tv/fp/D113543-fptoui.srctgt.ll
This fixes bugs reported in https://reviews.llvm.org/D113543.
fptosi/fptoui's poison checking expressions were as follows:
```
expr bv  = val.fp2sint(to_type.bits());
expr fp2 = bv.sint2fp(val);
// -0.0 is converted to 0 and then to 0.0, though -0.0 is ok to convert
return { move(bv), val.isFPZero() || fp2 == val.roundtz() };
```
If the input (`val`) was -0.5, `bv` is 0, `fp2` is +0.0.
Therefore, `fp2 == val.roundtz()` is false because `val.roundtz()` is -0.0.
To fix this, the poison condition's first part (`val.isFPZero()`) is replaced with a range check.
=> fptosi/fptoui must convert (-1.0, -0.0) to 0, not poison

tools/transform.cpp
std::bit_width is is defined in <bit> and used in the file.
The missing include can cause build failures with certain libc++
versions, as it is not included by accident through some other includes.
=> Add missing include of <bit>

tools/alive-tv.cpp
According to the issue: https://github.com/AliveToolkit/alive2/issues/799
Description of --passes parameter updated. A link to its official doc added.
@regehr
=> Passes description updated

tv/tv.cpp
pass when an unsound transformation is detected
this'll conflict with my other patch from today but resolving is trivial, I'm happy to fix which ever one lands second
=> linux-specific code for printing the command line args from the opt

llvm_util/known_fns.cpp
Attempt to fix the following build issue that occurs with latest version of llvm
```
regehr@ohm:~/alive2-nader/build$ ninja
[45/71] Building CXX object CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o
FAILED: CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o 
/home/regehr/llvm-project-14.0.6.src/build/bin/clang++  -I/home/regehr/alive2-nader -I/home/regehr/alive2-nader/build -I/home/regehr/llvm-project/llvm/include -I/home/regehr/llvm-project/for-alive/include -I/home/regehr/llvm-project/for-alive/lib -Wall -Werror -fPIC -fstrict-enums  -O3 -O3    -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++20 -MD -MT CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o -MF CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o.d -o …
```
=> fix build with latest version of llvm

llvm_util/cmd_args_def.h, llvm_util/cmd_args_list.h, scripts/alivecc.in, tv/tv.cpp
want to look this over Nuno? it works for a few examples I tried (in the sense that it dumps a bitcode file that repros the original error using the pass that's printed) but I don't want to polish if it's not what you're looking for here
=> save IR file to disk when encountering an unsoundness

llvm_util/llvm2alive.cpp
if clang is wrong here then this isn't the correct fix, but this is stopping me from building latest alive2 using clang
=> fix build failure due to unused capture signaled by clang

tools/alive-tv.cpp, tv/tv.cpp
if there was exactly 1 of these, now it works for multiple of them,
but it won't work if they get added/removed/reordered between the
two files -- but we handle signature mismatches gracefully so I think
this is fine
this addresses issue #828
=> deal more gracefully with un-named functions. before this only worked

llvm_util/llvm2alive.cpp, llvm_util/llvm2alive.h, tests/alive-tv/unsupported.metadata.in.src.srctgt.ll, tests/alive-tv/unsupported.metadata.in.tgt.srctgt.ll, tools/alive-exec.cpp, tools/alive-tv.cpp, tv/tv.cpp
Unsupported metadata in @tgt only should not block verification, as LLVM
IR metadata can be dropped without impacting semantics of the IR
function itself.
In particular, if @tgt can be verified as incorrect without unsupported
metadata, then extra metadata cannot turn the function into a 'correct'
one.
One instance where unsupported metadata can block verification at moment
are transformations that introduce new metadata, like for example
loop-vectorize, which may add !noalias metadata.
=> Ignore unsupported metadata in target functions.

scripts/rewritepass.py
this is needed to make tests run on my M1 Mac
I also had to create `python` as a symlink to `python3` -- we might just hardcode python3 instead of python to save people the trouble?
=> M1 Mac doesn't put python in /usr/bin

tools/alive-exec.cpp
alive-exec pulls in some cache stuff due to including our header file for command line options -- so give it a unique_ptr to a cache to keep it happy. it will never instantiate this.
=> fix the build on OSX

CMakeLists.txt
patch on my Linux box, libcache.a can't find crc_update()
=> argh-- burned by order of libraries in the link line, without this

smt/expr.cpp
Incorrect results were returned when encountering an `icmp ugt` instruction with the maximum uint64 value as its second operand.
For example, these incorrectly verify as equivalent functions ([https://alive2.llvm.org/ce/z/VmnnF_](https://alive2.llvm.org/ce/z/VmnnF_)):
```llvm
define i1 @src(i128 %L)  {
; ugt with max uint64 value, decimal 18446744073709551615 = 2^64-1
%ugt = icmp ugt i128 %L, u0xffffffffffffffff 
ret i1 %ugt
}
define i1 @tgt(i128 %L) {
ret i1 1
}
```
Another example compares ugt with not ule, this should verify but does not: https://alive2.llvm.org/ce/z/6JPbFD
This is caused by overflowing the `n+1` operation in the optimisation case, leading to >= 0 which is always true. Ensuring n is less than the maximum before adding fixes these behaviours.
=> Fix soundness bug due to overflow in expr::ugt() optimisation.

llvm_util/llvm2alive.cpp
I didn't see an immediate way to use getValueOrOne() here
=> fix another deprecation.

tools/quick-fuzz.cpp
this puts the fuzzers into classes, which is nicer because their state is encapsulated and easy to initialize. I made a separate class for the random instruction generator because I want to call it from both of the other fuzzers, this isn't very nice yet, but might work out. the only functional change here is that I added some optional support for the value fuzzer fetching some of its inputs from memory instead of getting them directly through function arguments, and then it also stores things randomly back to RAM.
=> fuzzer refactoring

llvm_util/llvm2alive.cpp
discussion here:
https://discourse.llvm.org/t/what-is-the-status-of-dbg-addr/62898
=> remove dbg_addr, which has been removed from LLVM

tools/quick-fuzz.cpp
the code was masking a 32 bit shift using 63, a 64 bit shift using 127, etc, creating more poison values than we wanted to deal with
this fixes that
=> fix off by one

tests/alive-tv/ssub-cmp-zero.v0.srctgt.ll, tests/alive-tv/ssub-cmp-zero.v1.srctgt.ll, tests/alive-tv/sub-is-not.srctgt.ll, tools/alive-tv.cpp
Change:
Instead of only searching for 'src' and 'tgt' in single-file mode, search for an arbitrary number of pairs of 'src{+d}', 'tgt{+d}'.
I.e if have the following functions in a file:
```
define @src {}
define @tgt {}
define @src2 {}
define @tgt2 {}
define @src3 {}
define @tgt3 {}
define @src4 {}
define @tgt5 {}
```
Alive2 will have the following pairs: 'src'/'tgt', 'src2'/'tgt2', and 'src3'/'tgt3'. It will ignore 'src4' and 'tgt5'.
Motivation:
This just a QOL change. A lot of LLVM patches have assosiated alive2 links. In some cases there need to be many links (i.e https://reviews.llvm.org/D149521).
Being able to specify multiple 'src'/'tgt' pairs in a single file would enable verifying multiple cases with a single link making it easier.
=> Enable multiple 'src'/'tgt' pairs in a single source

util/spaceship.h
The Xcode 14.3 release candidate is available
(https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes)
It requires the following changes to build Alive2.
=> Fix build failure with Xcode 14.3 release candidate.

scripts/opt-alive.sh.in
timeout doesn't exist on Darwin platforms, so it shouldn't be used.
=> Only define TIMEOUT on non-Darwin platforms.

ir/function.cpp, ir/function.h, tests/alive-tv/loops/partial_sub_loop_test_branch_loop.srctgt.ll
This patch fixes a [failing example](https://github.com/AliveToolkit/alive2/issues/748#issuecomment-1372248300) mentioned in issue [#748](https://github.com/AliveToolkit/alive2/issues/748). The original issue had likely gotten "fixed" by accident before this patch, so I only refer to that specific example, but it affects any code with nested loops (though sometimes the problem may not manifest itself).
Here is the reduced example:
```llvm
define i32 @partial_sub_loop_test_branch_loop(i32 %end) {
entry:
br label %outer_header
outer_header:
%j = phi i32 [0, %entry], [%j.inc, %outer_backedge]
br label %preheader
preheader:
br label %header
header:
%i = phi i32 [0, %preheader], [%i.inc, %backedge]
br label %backedge
backedge:
%i.inc = add i32 %i, 1
%cmp = icmp slt i32 %i.inc, %end
br i1 %cmp, …
```
=> Take loop exit blocks into account in constructing edges for top sort when dealing with a loop header

util/compiler.cpp
`unsigned long` is 32bit on many 32bit platforms.
Use `unsigned long long` instead.
=> Fix build on 32-bit platforms

ir/attrs.h
GCC 11 complains about allocsize_0 being uninitialized. I don't see any place where the uninitialized value is actually used, but let's silence the compiler warning anyway.
=> Silence a compiler warning

CMakeLists.txt
I'm in the process of trying to get alive2 available in the JuliaLang binary distribution system [1]. That system would like all relevant targets to be INSTALL'ed, so add appropriate CMake directives.
[1] https://github.com/JuliaPackaging/Yggdrasil/pull/4271
=> cmake: Set targets to INSTALL

smt/smt.h, tools/alive_lexer.h
This resolves a compilation error experienced on Fedora 38 due to lack of type definition for uint64_t.
=> Add include of cstdint to resolve definition of uint64_t

tools/alive-exec.cpp
the cache gets referred to from `llvm_util/cmd_args_def.h` so we have to define/declare that stuff
=> fix broken build

README.md
- and other hard-coded directories.
- Add official links for prerequisites.
- Add the obvious Ninja build steps.
- Note X86-centricity.
I’ve tested these on Mac and Linux up to the TV Build instructions, at which point I get CMake and/or linkage problems, but that’s presumably a separate issue.
=> Tweak ReadMe: Variablize uses of ~/llvm in the build instructions,

README.md
-  Troubleshooting suggestion for Mac dynamic_lookup/chained fixups linker warning and subsequent “symbol not found in flat namespace” crash.     Thanks to @ronaldoussoren (https://github.com/python/cpython/issues/97524#issuecomment-1291003452). 
- Example command for Mac with the new pass manager and a real file.
I’m not submitting my change to the CMake file (https://github.com/FlashSheridan/alive2/commit/7c642778), since it presumably isn’t affecting most users and might be a performance hit.  Feel free to pull it if you disagree.
=> ReadMe: Mac deployment workaround, new PM example

CMakeLists.txt, README.md
* Report CMAKE_PREFIX_PATH, since the error message with BUILD_TV set can be puzzling if you forget to set this.
* More ReadMe troubleshooting tips, especially for those of us whose forks are not at ToT, or are not [hastily updating to the latest MacOS](https://www.linkedin.com/pulse/era-update-automatically-over-rant-flash-sheridan/).
=> Friendlier CMake output and ReadMe tips

llvm_util/llvm2alive.cpp, tests/alive-tv/assume/assert.srctgt.ll
for @llvm.assume, but LLVM doesn't have any semantics for it, so treats it as opaque, so we don't have to worry about LLVM removing it
=> as Nuno suggested, add @llvm.assert which in Alive is just an alias

README.md
* Instructions for using the Alive2 IR in its log files to find LLVM IR for use in diagnosing unsoundness reports, especially with the Alive2 Compiler Explorer instance.
* Also unwrap a link broken by wrapping.
=> ReadMe: Diagnosing Unsoundness Reports

README.md, llvm_util/llvm2alive.cpp, scripts/opt-alive.sh.in
* Add `--verbose` and `--no-timeout` options for `opt-alive.sh`.
* Add them to the ReadMe and warn about timeout limitations.
* Also add the include file which [llvm::PossiblyNonNegInst Class Reference](https://llvm.org/docs/doxygen/classllvm_1_1PossiblyNonNegInst.html) documents, though that wasn’t what broke my build.
I’m not sure how to add tests for this.  Some of the infrastructure seems to rely on Python 2, which (no matter how much I miss it), I should probably not install on my work machine.
=> --verbose and --no-timeout options for opt-alive.sh

ir/instr.cpp, ir/instr.h, llvm_util/llvm2alive.cpp, tests/alive-tv/disjoint.srctgt.ll
This patch adds support for `disjoint` flags recently introduced by https://github.com/llvm/llvm-project/pull/72583.
See also https://llvm.org/docs/LangRef.html#or-instruction.
=> Add support for disjoint

README.md
Note in the ReadMe:
- Experimentation with SDK versions as well as compiler versions and vendors, when working around build breakages.
- Occasional need to copy metadata, which may be much later in the file, or sometimes absent.  (In which case, subject to correction, I delete it.)
- Possibility of appending other `opt` options, such as other optimizations.  (This looks promising for finding unsoundness in our fork’s use of O3, our normal optimization, though of course it can invalidate Lit pass/fail reports.)
=> ReadMe: metadata, SDK, appending other opt options

tools/alive-tv.cpp
and then -Werror is failing the build. this fix should be harmless.
=> startswith() now gives a warning on my machine due to being deprecated

llvm_util/cmd_args_def.h, llvm_util/cmd_args_list.h, tools/transform.cpp, util/config.cpp, util/config.h
I think this is a really important usability thing for Alive users
=> unconditionally check for source functions that are UB for all executions, but don't error out

README.md
I just built LLVM and `alive-tv` locally on a M2 chip (`aarch64`) after removing `-DLLVM_TARGETS_TO_BUILD=X86` and confirmed that `alive-tv` works. So I guess the flag can be removed? If I'm not mistaken, LLVM will automatically infer these targets on X86 systems anyway.
=> Remove X86 setting from README.md

README.md, llvm_util/cmd_args_list.h
- Note the `-smt-to:` option to the `alive` executable; corrects my c46e7ef.
- Add “in ms” to `alive-tv --help` for `-smt-to`.
- Note in build instructions that `BUILD_SHARED_LIBS` may not be necessary; it wasn’t for our build system, and caused severe problems when enabled.
-  Move its CMake problems to the instructions from Troubleshooting.
- Convert `alive-tv` example instructions into text which can be triple-clicked and dragged.  (I’ve started using it a lot; it found an important bug which had been fixed while I was fiddling with the build system.)
- Convert Compiler Explorer instance URL into a Markdown clickable link.  (Though I expect it will be made clickable anyway for most viewers by GitHub.)
=> ReadMe, `alive-tv --help`:  correct timeout, BUILD_SHARED_LIBS optional

README.md, llvm_util/cmd_args_def.h, scripts/opt-alive.sh.in
- Fix my 101be628 to redirect verbose `opt-alive.sh` output to stderr, since Lit can swallow it.
- Output report name to stderr in cmd_args_def.h (with a slightly different caption, and white space to make it prominent), since the output at tv.cpp:425 seems to have stopped working.  (Changing it to stderr didn’t work, and an Xcode breakpoint at that line was not hit when running under Lit, so it doesn’t seem to be an output redirection issue.)  It used to work at roughly bc51b72c.
- Add build hints for Xcode. 
- Recommend disabling “Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'unsigned int'” warnings, since there are a dozen of them and they break the build with the default warnings as errors, which I’ll file …
=> opt-alive.sh --verbose to stderr, hints on building with Xcode

README.md
- Hints for uniquing unsoundness reports.
- Cover `alive-tv` as well as Compiler Explorer instance. 
- Mention Nikita Popov’s `-allow-incomplete-ir` option, which makes some of my grumbling obsolete.
=> Hints for uniquing unsoundness reports

ir/instr.cpp, ir/instr.h, llvm_util/llvm2alive.cpp, tests/alive-tv/nsw.trunc.srctgt.ll, tests/alive-tv/nuw.trunc.srctgt.ll
Nowrap poison-generating flags to `trunc` have been recently introduced in LLVM.
=> Add support for nowrap flags to `trunc`

README.md
I know it says at the top that a recent version of LLVM is required, but I don't think it hurts to repeat this lower down in the README
=> repeat the LLVM version

llvm_util/llvm2alive.cpp, tests/alive-tv/calls/noundef-range.srctgt.ll
See the following code:
https://github.com/AliveToolkit/alive2/blob/22bc6f2791796708cbcfc99935992145f4ae2800/llvm_util/llvm2alive.cpp#L113-L123
alive2 returns node `assume_welldefined` instead of the original value when `noundef` exists.
https://github.com/AliveToolkit/alive2/blob/22bc6f2791796708cbcfc99935992145f4ae2800/llvm_util/llvm2alive.cpp#L1754-L1763
However, `alive_i` will be set to `assume_welldefined`, which causes type checks to fail when handing metadata of a call.
This patch bypasses `assume_welldefined` to set `alive_i` to the original value.
Fixes https://github.com/AliveToolkit/alive2/issues/1043.
=> Bypass assume_welldefined to handle metadata correctly

llvm_util/cmd_args_def.h
There is redundancy in the code that sets the value of the `config::src_unroll_cnt` variable.
=> remove duplicate code on cmd_args_def.h

smt/solver.cpp, smt/solver.h, tools/transform.cpp, util/file.cpp, util/file.h
Adds prefixes to the output files of `--smt-bench` in order to make it easier to find the query you are looking for. Output files are named `<QUERY_NAME>_<RANDOM_STRING>.smt2`. The query names are also shown when using `--smt-verbose`.
=> Add named queries

ir/instr.h
As proposed previously in https://github.com/AliveToolkit/alive2/issues/1075, this PR adds the missing getters for instructions.
=> Add missing getters

ir/instr.cpp, ir/instr.h
As proposed previously in https://github.com/AliveToolkit/alive2/issues/1075, this PR adds the `Instr::isTerminator` method.
It currently does not consider `unreachable` a terminator, as it is represented as `assume i1 0` in Alive2 IR. This instruction may also be generated by `__builtin_assume(false)`, in which case it is not a terminator in LLVM IR. Thus not every basic block in alive2 necessarily ends with a terminator (at least as it is implemented currently).
=> Add Instr::isTerminator

llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/noundef-ret5.srctgt.ll
Fixes a false positive result with `noundef` on the return value of `llvm.fshl`: https://alive2.llvm.org/ce/z/OfZuDi
```
define i64 @src(i64 %x) {
%282 = call noundef i64 @llvm.fshl.i64(i64 %x, i64 %x, i64 3) 
%283 = and i64 %282, -4
ret i64 %283
}
define noundef i64 @tgt(i64 %x) {
%282 = call noundef i64 @llvm.fshl.i64(i64 %x, i64 %x, i64 3) 
%283 = and i64 %282, -4
ret i64 %283
}
```
```
----------------------------------------
define i64 @src(i64 %x) {
#0:
%#1 = fshl i64 %x, i64 %x, i64 3
%#2 = and i64 %#1, -4
ret i64 %#2
}
=>
define i64 @tgt(i64 %x) noundef {
#0:
%#1 = fshl i64 %x, i64 %x, i64 3
%#2 = and i64 %#1, -4
ret i64 %#2
}
Transformation doesn't verify!
ERROR: Source is more defined than target
Example:
i64 %x = poison
Source:
i64 %#1 = poison
i64 %#2 = poison
Target:
i64 %#1 …
```
=> Handle fnattr for all arithmetic intrinsics

ir/state.cpp, ir/state.h
As proposed previously in https://github.com/AliveToolkit/alive2/issues/1075, this PR adds the `State::getPath` method.
=> Add State::getPath

CMakeLists.txt, llvm_util/cmd_args_def.h, llvm_util/llvm2alive.cpp, util/compiler.cpp, util/file.cpp
These are some changes I had to make to build `alive-tv` with MSVC.
- `/Zc:__cplusplus` Sets the `__cplusplus` macro to the correct value.
- Since `parallel.hpp` uses UNIX APIs, we cannot build it. However this is not really an issue as it is only used when `BUILD_TV` is enabled, which is not supported on windows anyways.
- GCC intrinsics are of course not supported
- `std::filesystem::path` does not implicitly cast to string
=> Build alive-tv with MSVC

ir/memory.cpp, tests/alive-tv/memory/function_call_with_memory_attribute.srctgt.ll
Fixes https://github.com/AliveToolkit/alive2/issues/1087.
=> Fix : Copy missing local_blk_align, local_blk_size, local_blk_kind in dupNoRead function.

ir/instr.cpp, ir/instr.h
This PR adds `Phi::setValue` and `Phi::setSource` methods, that allow setting the incoming value / basic block for a specific index. In contrast to `replaceSourceWith` and `replace` to they run in $O(1)$ instead of $O(n)$.
Related: https://github.com/AliveToolkit/alive2/issues/1075
=> Add Phi::setValue and Phi::setSource

llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/range.srctgt.ll
For historical reasons we choose to use return value range attributes for `llvm.ctpop` instead of introducing a new poison-generating parameter (See https://github.com/llvm/llvm-project/issues/95255#issuecomment-2166944909).
This patch adds support for range attributes on the return value of an intrinsic call. Fixes https://github.com/AliveToolkit/alive2/issues/1096.
=> respect range attributes on the return value of an intrinsic call

ir/instr.cpp, ir/instr.h, llvm_util/llvm2alive.cpp, tests/alive-tv/samesign.srctgt.ll
RFC link: https://discourse.llvm.org/t/rfc-signedness-independent-icmps/81423
https://github.com/llvm/llvm-project/pull/111419 has been landed.
=> Add support for `samesign` flag

smt/expr.cpp, smt/expr.h
Similar to `sext`, `ashr` is also not rewritten to a combination of `extract` and `concat`s. The `extract` method already simplifies `extract(sext(...), ...)`. This PR extends `extract` to also simpliy `extract(ashr(...), ...)`. It adds the following rewrite:
`extract(ashr(x, shift), high, low) -> extract(x, high + shift, low + shift) if high + shift < x.bits()`
=> Simplify extract from ashr

tests/alive-tv/vector/vector-splat-literal.srctgt.ll
Vector splat literals have been introduced recently in LLVM, and the llvm_util in Alive2 already handles this. However, the test suite misses coverage for splat literals. Add a test, fixing this.
=> tv/vector/test: add test for vector splat literals

BugList.md, scripts/perf-testing/README.md, tests/README.md, tests/alive-tv/bugs/README.md
Description: This PR includes the following corrections:
Corrected "miscompilation" to "miscompilations" to match the plural form.
Capitalized the first letter of the sentence starting with "three test file formats are supported:".
Fixed the spelling of "coallesced" to "coalesced".
=> Correct Grammar, Spelling, and Capitalization in Documentation

ir/instr.cpp, ir/instr.h, llvm_util/llvm2alive.cpp, tests/alive-tv/fp/fpext-trunc.srctgt.ll, tests/alive-tv/fp/fptrunc-fmf-fail.srctgt.ll
See also https://github.com/llvm/llvm-project/pull/115894.
=> Add FMF support for fptrunc/fpext

BugList.md
Reviewed the entire repository, no more typos found in docs.
Best regards,
Bilogweb3
=> chore: correct typos docs

smt/expr.cpp, tests/alive-tv/samesign.srctgt.ll
`high + shift` may overflow when the shamt is invalid: https://alive2.llvm.org/ce/z/AT9VHM
Fix an assertion failure introduced by https://github.com/AliveToolkit/alive2/pull/1105.
=> Check shamt before extracting bits from an ashr

ir/instr.cpp, tests/alive-tv/samesign-ptr.srctgt.ll
Pointers should be interpreted as integral before extracting the sign bit.
Alive2: https://alive2.llvm.org/ce/z/GnWJ9H
```
----------------------------------------
define i1 @src(ptr %a, ptr %b) {
#0:
%pa = ptrtoint ptr %a to i8
%pb = ptrtoint ptr %b to i8
%sub = sub i8 %pb, %pa
%gep = gep ptr %a, 1 x i8 %sub
%cmp = icmp samesign eq ptr %gep, null
ret i1 %cmp
}
=>
define i1 @tgt(ptr %a, ptr %b) {
#0:
%cmp = icmp samesign eq ptr %b, null
ret i1 %cmp
}
Transformation doesn't verify!
ERROR: Target is more poisonous than source
Example:
ptr %a = null
ptr %b = pointer(non-local, block_id=2, offset=0) / Address=#x01
Source:
i8 %pa = #x00 (0)
i8 %pb = #x01 (1)
i8 %sub = #x01 (1)
ptr %gep = pointer(non-local, block_id=0, offset=1) / Address=#x01
i1 %cmp = #x0 (0)
SOURCE MEMORY STATE …
```
=> Fix false positive on icmp ptr with samesign flag

llvm_util/llvm2alive.cpp
- Resolves a null pointer dereference error observed in Clang v19.1.5 where the check is optimized away
- Add a separate null pointer check for the pointer returned by llvm_type2alive in llvm2alive_::run()
=> Fix crash from optimized null pointer access

llvm_util/cmd_args_def.h, llvm_util/compare.cpp, llvm_util/compare.h, tools/alive-exec.cpp, tools/alive-tv.cpp, tools/quick-fuzz.cpp, tools/transform.cpp, tv/tv.cpp, util/config.cpp, util/config.h
- Translation validation CLI quiet flag skips counter-example generation
- Update all Alive2 utilities to use util::config::quiet for consistency
=> Enhance translational validation pass quiet flag

llvm_util/llvm2alive.cpp
this gets Alive to build against current LLVM by mapping the new captures(none) to Alive's NoCapture.
this PR leaves undone two additional items
- upgrade our test cases correspondingly (right now this is taken care of by the parser, so no rush)
-  support captures() other than none -- this is more work
=> support captures(none) instead of nocapture

ir/instr.cpp, tests/unit/fp/frem.opt
This patch implements `fmod` by using `remainder` as suggested by https://en.cppreference.com/w/c/numeric/math/fmod:
```
double fmod(double x, double y)
{
#pragma STDC FENV_ACCESS ON
double result = remainder(x), (y = fabs(y)));
if (signbit(result))
result += y;
return copysign(result, x);
}
```
Test cases are derived from https://en.cppreference.com/w/c/numeric/math/fmod and https://github.com/llvm/llvm-project/blob/0252d338fa9f4f2f1262b5f7d8158e3f5857fcaf/llvm/unittests/ADT/APFloatTest.cpp#L4377.
Closes https://github.com/AliveToolkit/alive2/issues/1175.
=> Remove frem approximation

llvm_util/llvm2alive.cpp
explicit cast needed because LLVM changed the InlineAsm API to return StringRefs instead of std::strings
=> keep up with LLVM API change

ir/attrs.cpp, ir/attrs.h, ir/instr.cpp, ir/memory.cpp, ir/memory.h, llvm_util/llvm2alive.cpp, tests/alive-tv/attrs/dead-on-return-param.srctgt.ll
`dead_on_return` attribute was recently introduced in LLVM.
=> Memset to poison `dead_on_return` ptr arguments
